import type { ActionDefinition } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";
import { defineProviderAction } from "../../core/provider-definition.ts";

const service = "loyjoy";

const processSchema = s.looseObject("A LoyJoy process (agent) returned by the API.");
const viewSchema = s.looseObject("A LoyJoy home view returned by the API.");
const chunkSchema = s.looseObject("A knowledge chunk returned by LoyJoy search.");
const variablesSchema = s.looseObject("Process variables keyed by the variable names configured in LoyJoy.");

export const loyjoyActions: ActionDefinition[] = [
  defineProviderAction(service, {
    name: "list_processes",
    description: "List the published LoyJoy processes (agents) available in the tenant.",
    requiredScopes: [],
    inputSchema: s.object("No input is required to list LoyJoy processes.", {}),
    outputSchema: s.object("The published LoyJoy processes available in the tenant.", {
      processes: s.array("Process records returned by LoyJoy.", processSchema),
    }),
  }),
  defineProviderAction(service, {
    name: "get_process",
    description: "Retrieve a published LoyJoy process (agent) as JSON by its ID.",
    requiredScopes: [],
    inputSchema: s.object("Input for retrieving a LoyJoy process.", {
      processId: s.uuid("The ID of the published process to retrieve."),
    }),
    outputSchema: s.object("A published LoyJoy process.", {
      process: processSchema,
    }),
  }),
  defineProviderAction(service, {
    name: "start_process",
    description:
      "Start a published LoyJoy process and return the variables produced before it completes or requests user input.",
    requiredScopes: [],
    inputSchema: s.object(
      "Input for starting a published LoyJoy process.",
      {
        processId: s.uuid("The ID of the published process to start."),
        variables: variablesSchema,
      },
      { optional: ["variables"] },
    ),
    outputSchema: s.object("The variables returned after starting the LoyJoy process.", {
      variables: s.unknown("The process variables returned by LoyJoy."),
    }),
  }),
  defineProviderAction(service, {
    name: "list_views",
    description: "List the LoyJoy home views available in the tenant.",
    requiredScopes: [],
    inputSchema: s.object("No input is required to list LoyJoy home views.", {}),
    outputSchema: s.object("The LoyJoy home views available in the tenant.", {
      views: s.array("Home view records returned by LoyJoy.", viewSchema),
    }),
  }),
  defineProviderAction(service, {
    name: "get_view",
    description: "Retrieve a LoyJoy home view as JSON by its ID.",
    requiredScopes: [],
    inputSchema: s.object("Input for retrieving a LoyJoy home view.", {
      viewId: s.uuid("The ID of the home view to retrieve."),
    }),
    outputSchema: s.object("A LoyJoy home view.", {
      view: viewSchema,
    }),
  }),
  defineProviderAction(service, {
    name: "search_chunks",
    description: "Search the tenant knowledge base for up to 100 relevant chunks.",
    requiredScopes: [],
    inputSchema: s.object(
      "Input for searching LoyJoy knowledge chunks.",
      {
        query: s.nonEmptyString("The natural-language search query."),
        folders: s.stringArray("Folder names used to restrict the knowledge search."),
        maxChunks: s.integer("The maximum number of chunks to return, up to 100.", {
          minimum: 1,
          maximum: 100,
        }),
      },
      { optional: ["folders", "maxChunks"] },
    ),
    outputSchema: s.object("Knowledge chunks matching the search query.", {
      chunks: s.array("Knowledge chunks returned by LoyJoy.", chunkSchema),
    }),
  }),
  defineProviderAction(service, {
    name: "create_completion",
    description: "Generate completion text with a published LoyJoy process (agent).",
    requiredScopes: [],
    inputSchema: s.object(
      "Input for generating text with a published LoyJoy process.",
      {
        processId: s.uuid("The ID of the published process used for the completion."),
        text: s.nonEmptyString("The input text to complete."),
        locale: s.nonEmptyString("The locale used for generation, such as en or de."),
      },
      { optional: ["locale"] },
    ),
    outputSchema: s.object("Completion text generated by LoyJoy.", {
      text: s.string("The generated completion text."),
    }),
  }),
];
