// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const adminOperations: readonly DokployOperationDefinition[] = [
  {
    name: "admin-setupMonitoring",
    operationId: "admin-setupMonitoring",
    tag: "admin",
    description: "Modify Dokploy state via POST /admin.setupMonitoring.",
    method: "POST",
    path: "/admin.setupMonitoring",
    pathFields: [],
    queryFields: [],
    bodyFields: ["metricsConfig"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        metricsConfig: {
          type: "object",
          properties: {
            server: {
              type: "object",
              properties: {
                refreshRate: {
                  type: "number",
                  minimum: 2,
                },
                port: {
                  type: "number",
                  minimum: 1,
                },
                token: {
                  type: "string",
                },
                urlCallback: {
                  type: "string",
                  format: "uri",
                },
                retentionDays: {
                  type: "number",
                  minimum: 1,
                },
                cronJob: {
                  type: "string",
                  minLength: 1,
                },
                thresholds: {
                  type: "object",
                  properties: {
                    cpu: {
                      type: "number",
                      minimum: 0,
                    },
                    memory: {
                      type: "number",
                      minimum: 0,
                    },
                  },
                  required: ["cpu", "memory"],
                },
              },
              required: ["refreshRate", "port", "token", "urlCallback", "retentionDays", "cronJob", "thresholds"],
            },
            containers: {
              type: "object",
              properties: {
                refreshRate: {
                  type: "number",
                  minimum: 2,
                },
                services: {
                  type: "object",
                  properties: {
                    include: {
                      type: "array",
                      items: {
                        type: "string",
                      },
                    },
                    exclude: {
                      type: "array",
                      items: {
                        type: "string",
                      },
                    },
                  },
                },
              },
              required: ["refreshRate", "services"],
            },
          },
          required: ["server", "containers"],
        },
      },
      additionalProperties: false,
      description: "Input for admin-setupMonitoring.",
      required: ["metricsConfig"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
