// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const aiOperations: readonly DokployOperationDefinition[] = [
  {
    name: "ai-one",
    operationId: "ai-one",
    tag: "ai",
    description: "Read Dokploy data via GET /ai.one.",
    method: "GET",
    path: "/ai.one",
    pathFields: [],
    queryFields: ["aiId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        aiId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for ai-one.",
      required: ["aiId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-getModels",
    operationId: "ai-getModels",
    tag: "ai",
    description: "Read Dokploy data via GET /ai.getModels.",
    method: "GET",
    path: "/ai.getModels",
    pathFields: [],
    queryFields: ["apiUrl", "apiKey"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        apiUrl: {
          type: "string",
          minLength: 1,
        },
        apiKey: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for ai-getModels.",
      required: ["apiKey", "apiUrl"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-create",
    operationId: "ai-create",
    tag: "ai",
    description: "Modify Dokploy state via POST /ai.create.",
    method: "POST",
    path: "/ai.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["name", "apiUrl", "apiKey", "model", "isEnabled"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        apiUrl: {
          type: "string",
          format: "uri",
        },
        apiKey: {
          type: "string",
        },
        model: {
          type: "string",
          minLength: 1,
        },
        isEnabled: {
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for ai-create.",
      required: ["apiKey", "apiUrl", "isEnabled", "model", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-update",
    operationId: "ai-update",
    tag: "ai",
    description: "Modify Dokploy state via POST /ai.update.",
    method: "POST",
    path: "/ai.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["aiId", "name", "apiUrl", "apiKey", "model", "isEnabled", "createdAt"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        aiId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
          minLength: 1,
        },
        apiUrl: {
          type: "string",
          format: "uri",
        },
        apiKey: {
          type: "string",
        },
        model: {
          type: "string",
          minLength: 1,
        },
        isEnabled: {
          type: "boolean",
        },
        createdAt: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for ai-update.",
      required: ["aiId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-getAll",
    operationId: "ai-getAll",
    tag: "ai",
    description: "Read Dokploy data via GET /ai.getAll.",
    method: "GET",
    path: "/ai.getAll",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for ai-getAll.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-get",
    operationId: "ai-get",
    tag: "ai",
    description: "Read Dokploy data via GET /ai.get.",
    method: "GET",
    path: "/ai.get",
    pathFields: [],
    queryFields: ["aiId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        aiId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for ai-get.",
      required: ["aiId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-delete",
    operationId: "ai-delete",
    tag: "ai",
    description:
      "Modify Dokploy state via POST /ai.delete. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/ai.delete",
    pathFields: [],
    queryFields: [],
    bodyFields: ["aiId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        aiId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for ai-delete.",
      required: ["aiId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-getEnabledProviders",
    operationId: "ai-getEnabledProviders",
    tag: "ai",
    description: "Read Dokploy data via GET /ai.getEnabledProviders.",
    method: "GET",
    path: "/ai.getEnabledProviders",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for ai-getEnabledProviders.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-analyzeLogs",
    operationId: "ai-analyzeLogs",
    tag: "ai",
    description: "Modify Dokploy state via POST /ai.analyzeLogs.",
    method: "POST",
    path: "/ai.analyzeLogs",
    pathFields: [],
    queryFields: [],
    bodyFields: ["aiId", "logs", "context"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        aiId: {
          type: "string",
          minLength: 1,
        },
        logs: {
          type: "string",
          minLength: 1,
        },
        context: {
          type: "string",
          enum: ["build", "runtime"],
        },
      },
      additionalProperties: false,
      description: "Input for ai-analyzeLogs.",
      required: ["aiId", "context", "logs"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-testConnection",
    operationId: "ai-testConnection",
    tag: "ai",
    description: "Modify Dokploy state via POST /ai.testConnection.",
    method: "POST",
    path: "/ai.testConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["apiUrl", "apiKey", "model"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        apiUrl: {
          type: "string",
          minLength: 1,
        },
        apiKey: {
          type: "string",
        },
        model: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for ai-testConnection.",
      required: ["apiKey", "apiUrl", "model"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-suggest",
    operationId: "ai-suggest",
    tag: "ai",
    description: "Modify Dokploy state via POST /ai.suggest.",
    method: "POST",
    path: "/ai.suggest",
    pathFields: [],
    queryFields: [],
    bodyFields: ["aiId", "input", "serverId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        aiId: {
          type: "string",
        },
        input: {
          type: "string",
        },
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for ai-suggest.",
      required: ["aiId", "input"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "ai-deploy",
    operationId: "ai-deploy",
    tag: "ai",
    description: "Modify Dokploy state via POST /ai.deploy.",
    method: "POST",
    path: "/ai.deploy",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "environmentId",
      "id",
      "dockerCompose",
      "envVariables",
      "serverId",
      "name",
      "description",
      "domains",
      "configFiles",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        environmentId: {
          type: "string",
          minLength: 1,
        },
        id: {
          type: "string",
          minLength: 1,
        },
        dockerCompose: {
          type: "string",
          minLength: 1,
        },
        envVariables: {
          type: "string",
        },
        serverId: {
          type: "string",
        },
        name: {
          type: "string",
          minLength: 1,
        },
        description: {
          type: "string",
        },
        domains: {
          type: "array",
          items: {
            type: "object",
            properties: {
              host: {
                type: "string",
                minLength: 1,
              },
              port: {
                type: "number",
                minimum: 1,
              },
              serviceName: {
                type: "string",
                minLength: 1,
              },
            },
            required: ["host", "port", "serviceName"],
          },
        },
        configFiles: {
          type: "array",
          items: {
            type: "object",
            properties: {
              filePath: {
                type: "string",
                minLength: 1,
              },
              content: {
                type: "string",
                minLength: 1,
              },
            },
            required: ["filePath", "content"],
          },
        },
      },
      additionalProperties: false,
      description: "Input for ai-deploy.",
      required: ["description", "dockerCompose", "envVariables", "environmentId", "id", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
