// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const auditLogOperations: readonly DokployOperationDefinition[] = [
  {
    name: "auditLog-all",
    operationId: "auditLog-all",
    tag: "auditLog",
    description: "Read Dokploy data via GET /auditLog.all.",
    method: "GET",
    path: "/auditLog.all",
    pathFields: [],
    queryFields: ["userId", "userEmail", "resourceName", "action", "resourceType", "from", "to", "limit", "offset"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        userId: {
          type: "string",
        },
        userEmail: {
          type: "string",
        },
        resourceName: {
          type: "string",
        },
        action: {
          type: "string",
          enum: ["create", "update", "delete", "deploy", "cancel", "redeploy", "login", "logout"],
        },
        resourceType: {
          type: "string",
          enum: [
            "project",
            "service",
            "environment",
            "deployment",
            "user",
            "customRole",
            "domain",
            "certificate",
            "registry",
            "server",
            "sshKey",
            "gitProvider",
            "notification",
            "settings",
            "session",
          ],
        },
        from: {
          type: "string",
        },
        to: {
          type: "string",
        },
        limit: {
          default: 50,
          type: "number",
          minimum: 1,
          maximum: 500,
        },
        offset: {
          default: 0,
          type: "number",
          minimum: 0,
        },
      },
      additionalProperties: false,
      description: "Input for auditLog-all.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
