// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const bitbucketOperations: readonly DokployOperationDefinition[] = [
  {
    name: "bitbucket-create",
    operationId: "bitbucket-create",
    tag: "bitbucket",
    description: "Modify Dokploy state via POST /bitbucket.create.",
    method: "POST",
    path: "/bitbucket.create",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "bitbucketId",
      "bitbucketUsername",
      "bitbucketEmail",
      "appPassword",
      "apiToken",
      "bitbucketWorkspaceName",
      "gitProviderId",
      "authId",
      "name",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        bitbucketId: {
          type: "string",
        },
        bitbucketUsername: {
          type: "string",
        },
        bitbucketEmail: {
          type: "string",
          format: "email",
          pattern:
            "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
        },
        appPassword: {
          type: "string",
        },
        apiToken: {
          type: "string",
        },
        bitbucketWorkspaceName: {
          type: "string",
        },
        gitProviderId: {
          type: "string",
        },
        authId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for bitbucket-create.",
      required: ["authId", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "bitbucket-one",
    operationId: "bitbucket-one",
    tag: "bitbucket",
    description: "Read Dokploy data via GET /bitbucket.one.",
    method: "GET",
    path: "/bitbucket.one",
    pathFields: [],
    queryFields: ["bitbucketId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        bitbucketId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for bitbucket-one.",
      required: ["bitbucketId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "bitbucket-bitbucketProviders",
    operationId: "bitbucket-bitbucketProviders",
    tag: "bitbucket",
    description: "Read Dokploy data via GET /bitbucket.bitbucketProviders.",
    method: "GET",
    path: "/bitbucket.bitbucketProviders",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for bitbucket-bitbucketProviders.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "bitbucket-getBitbucketRepositories",
    operationId: "bitbucket-getBitbucketRepositories",
    tag: "bitbucket",
    description: "Read Dokploy data via GET /bitbucket.getBitbucketRepositories.",
    method: "GET",
    path: "/bitbucket.getBitbucketRepositories",
    pathFields: [],
    queryFields: ["bitbucketId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        bitbucketId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for bitbucket-getBitbucketRepositories.",
      required: ["bitbucketId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "bitbucket-getBitbucketBranches",
    operationId: "bitbucket-getBitbucketBranches",
    tag: "bitbucket",
    description: "Read Dokploy data via GET /bitbucket.getBitbucketBranches.",
    method: "GET",
    path: "/bitbucket.getBitbucketBranches",
    pathFields: [],
    queryFields: ["owner", "repo", "bitbucketId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        owner: {
          type: "string",
        },
        repo: {
          type: "string",
        },
        bitbucketId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for bitbucket-getBitbucketBranches.",
      required: ["owner", "repo"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "bitbucket-testConnection",
    operationId: "bitbucket-testConnection",
    tag: "bitbucket",
    description: "Modify Dokploy state via POST /bitbucket.testConnection.",
    method: "POST",
    path: "/bitbucket.testConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["bitbucketId", "bitbucketUsername", "bitbucketEmail", "workspaceName", "apiToken", "appPassword"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        bitbucketId: {
          type: "string",
          minLength: 1,
        },
        bitbucketUsername: {
          type: "string",
        },
        bitbucketEmail: {
          type: "string",
          format: "email",
          pattern:
            "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
        },
        workspaceName: {
          type: "string",
        },
        apiToken: {
          type: "string",
        },
        appPassword: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for bitbucket-testConnection.",
      required: ["bitbucketId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "bitbucket-update",
    operationId: "bitbucket-update",
    tag: "bitbucket",
    description: "Modify Dokploy state via POST /bitbucket.update.",
    method: "POST",
    path: "/bitbucket.update",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "bitbucketId",
      "bitbucketUsername",
      "bitbucketEmail",
      "appPassword",
      "apiToken",
      "bitbucketWorkspaceName",
      "gitProviderId",
      "name",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        bitbucketId: {
          type: "string",
          minLength: 1,
        },
        bitbucketUsername: {
          type: "string",
        },
        bitbucketEmail: {
          type: "string",
          format: "email",
          pattern:
            "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
        },
        appPassword: {
          type: "string",
        },
        apiToken: {
          type: "string",
        },
        bitbucketWorkspaceName: {
          type: "string",
        },
        gitProviderId: {
          type: "string",
        },
        name: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for bitbucket-update.",
      required: ["bitbucketId", "gitProviderId", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
