// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const certificatesOperations: readonly DokployOperationDefinition[] = [
  {
    name: "certificates-create",
    operationId: "certificates-create",
    tag: "certificates",
    description: "Modify Dokploy state via POST /certificates.create.",
    method: "POST",
    path: "/certificates.create",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "certificateId",
      "name",
      "certificateData",
      "privateKey",
      "certificatePath",
      "autoRenew",
      "organizationId",
      "serverId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        certificateId: {
          type: "string",
        },
        name: {
          type: "string",
          minLength: 1,
        },
        certificateData: {
          type: "string",
          minLength: 1,
        },
        privateKey: {
          type: "string",
          minLength: 1,
        },
        certificatePath: {
          type: "string",
        },
        autoRenew: {
          anyOf: [
            {
              type: "boolean",
            },
            {
              type: "null",
            },
          ],
        },
        organizationId: {
          type: "string",
        },
        serverId: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for certificates-create.",
      required: ["certificateData", "name", "organizationId", "privateKey"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "certificates-one",
    operationId: "certificates-one",
    tag: "certificates",
    description: "Read Dokploy data via GET /certificates.one.",
    method: "GET",
    path: "/certificates.one",
    pathFields: [],
    queryFields: ["certificateId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        certificateId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for certificates-one.",
      required: ["certificateId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "certificates-remove",
    operationId: "certificates-remove",
    tag: "certificates",
    description:
      "Modify Dokploy state via POST /certificates.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/certificates.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["certificateId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        certificateId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for certificates-remove.",
      required: ["certificateId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "certificates-all",
    operationId: "certificates-all",
    tag: "certificates",
    description: "Read Dokploy data via GET /certificates.all.",
    method: "GET",
    path: "/certificates.all",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for certificates-all.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "certificates-update",
    operationId: "certificates-update",
    tag: "certificates",
    description: "Modify Dokploy state via POST /certificates.update.",
    method: "POST",
    path: "/certificates.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["certificateId", "name", "certificateData", "privateKey"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        certificateId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
          minLength: 1,
        },
        certificateData: {
          type: "string",
          minLength: 1,
        },
        privateKey: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for certificates-update.",
      required: ["certificateId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
