// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const customRoleOperations: readonly DokployOperationDefinition[] = [
  {
    name: "customRole-all",
    operationId: "customRole-all",
    tag: "customRole",
    description: "Read Dokploy data via GET /customRole.all.",
    method: "GET",
    path: "/customRole.all",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for customRole-all.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "customRole-create",
    operationId: "customRole-create",
    tag: "customRole",
    description: "Modify Dokploy state via POST /customRole.create.",
    method: "POST",
    path: "/customRole.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["roleName", "permissions"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        roleName: {
          type: "string",
          minLength: 1,
          maxLength: 50,
        },
        permissions: {
          type: "object",
          propertyNames: {
            type: "string",
          },
          additionalProperties: {
            type: "array",
            items: {
              type: "string",
            },
          },
        },
      },
      additionalProperties: false,
      description: "Input for customRole-create.",
      required: ["permissions", "roleName"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "customRole-update",
    operationId: "customRole-update",
    tag: "customRole",
    description: "Modify Dokploy state via POST /customRole.update.",
    method: "POST",
    path: "/customRole.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["roleName", "newRoleName", "permissions"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        roleName: {
          type: "string",
          minLength: 1,
        },
        newRoleName: {
          type: "string",
          minLength: 1,
          maxLength: 50,
        },
        permissions: {
          type: "object",
          propertyNames: {
            type: "string",
          },
          additionalProperties: {
            type: "array",
            items: {
              type: "string",
            },
          },
        },
      },
      additionalProperties: false,
      description: "Input for customRole-update.",
      required: ["permissions", "roleName"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "customRole-remove",
    operationId: "customRole-remove",
    tag: "customRole",
    description:
      "Modify Dokploy state via POST /customRole.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/customRole.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["roleName"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        roleName: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for customRole-remove.",
      required: ["roleName"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "customRole-membersByRole",
    operationId: "customRole-membersByRole",
    tag: "customRole",
    description: "Read Dokploy data via GET /customRole.membersByRole.",
    method: "GET",
    path: "/customRole.membersByRole",
    pathFields: [],
    queryFields: ["roleName"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        roleName: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for customRole-membersByRole.",
      required: ["roleName"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "customRole-getStatements",
    operationId: "customRole-getStatements",
    tag: "customRole",
    description: "Read Dokploy data via GET /customRole.getStatements.",
    method: "GET",
    path: "/customRole.getStatements",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for customRole-getStatements.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
