// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const deploymentOperations: readonly DokployOperationDefinition[] = [
  {
    name: "deployment-all",
    operationId: "deployment-all",
    tag: "deployment",
    description: "Read Dokploy data via GET /deployment.all.",
    method: "GET",
    path: "/deployment.all",
    pathFields: [],
    queryFields: ["applicationId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        applicationId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for deployment-all.",
      required: ["applicationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "deployment-allByCompose",
    operationId: "deployment-allByCompose",
    tag: "deployment",
    description: "Read Dokploy data via GET /deployment.allByCompose.",
    method: "GET",
    path: "/deployment.allByCompose",
    pathFields: [],
    queryFields: ["composeId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        composeId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for deployment-allByCompose.",
      required: ["composeId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "deployment-allByServer",
    operationId: "deployment-allByServer",
    tag: "deployment",
    description: "Read Dokploy data via GET /deployment.allByServer.",
    method: "GET",
    path: "/deployment.allByServer",
    pathFields: [],
    queryFields: ["serverId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        serverId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for deployment-allByServer.",
      required: ["serverId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "deployment-allCentralized",
    operationId: "deployment-allCentralized",
    tag: "deployment",
    description: "Read Dokploy data via GET /deployment.allCentralized.",
    method: "GET",
    path: "/deployment.allCentralized",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for deployment-allCentralized.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "deployment-queueList",
    operationId: "deployment-queueList",
    tag: "deployment",
    description: "Read Dokploy data via GET /deployment.queueList.",
    method: "GET",
    path: "/deployment.queueList",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for deployment-queueList.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "deployment-allByType",
    operationId: "deployment-allByType",
    tag: "deployment",
    description: "Read Dokploy data via GET /deployment.allByType.",
    method: "GET",
    path: "/deployment.allByType",
    pathFields: [],
    queryFields: ["id", "type"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
          minLength: 1,
        },
        type: {
          type: "string",
          enum: ["application", "compose", "server", "schedule", "previewDeployment", "backup", "volumeBackup"],
        },
      },
      additionalProperties: false,
      description: "Input for deployment-allByType.",
      required: ["id", "type"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "deployment-killProcess",
    operationId: "deployment-killProcess",
    tag: "deployment",
    description:
      "Modify Dokploy state via POST /deployment.killProcess. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/deployment.killProcess",
    pathFields: [],
    queryFields: [],
    bodyFields: ["deploymentId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        deploymentId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for deployment-killProcess.",
      required: ["deploymentId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "deployment-removeDeployment",
    operationId: "deployment-removeDeployment",
    tag: "deployment",
    description:
      "Modify Dokploy state via POST /deployment.removeDeployment. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/deployment.removeDeployment",
    pathFields: [],
    queryFields: [],
    bodyFields: ["deploymentId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        deploymentId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for deployment-removeDeployment.",
      required: ["deploymentId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
