// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const destinationOperations: readonly DokployOperationDefinition[] = [
  {
    name: "destination-create",
    operationId: "destination-create",
    tag: "destination",
    description: "Modify Dokploy state via POST /destination.create.",
    method: "POST",
    path: "/destination.create",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "name",
      "provider",
      "accessKey",
      "bucket",
      "region",
      "endpoint",
      "secretAccessKey",
      "additionalFlags",
      "serverId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        provider: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        accessKey: {
          type: "string",
        },
        bucket: {
          type: "string",
        },
        region: {
          type: "string",
        },
        endpoint: {
          type: "string",
        },
        secretAccessKey: {
          type: "string",
        },
        additionalFlags: {
          anyOf: [
            {
              default: [],
              type: "array",
              items: {
                type: "string",
                pattern: "^--[a-zA-Z0-9-]+(=[a-zA-Z0-9._:/@-]+)?$",
              },
            },
            {
              type: "null",
            },
          ],
        },
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for destination-create.",
      required: ["accessKey", "additionalFlags", "bucket", "endpoint", "name", "provider", "region", "secretAccessKey"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "destination-testConnection",
    operationId: "destination-testConnection",
    tag: "destination",
    description: "Modify Dokploy state via POST /destination.testConnection.",
    method: "POST",
    path: "/destination.testConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "name",
      "provider",
      "accessKey",
      "bucket",
      "region",
      "endpoint",
      "secretAccessKey",
      "additionalFlags",
      "serverId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        provider: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        accessKey: {
          type: "string",
        },
        bucket: {
          type: "string",
        },
        region: {
          type: "string",
        },
        endpoint: {
          type: "string",
        },
        secretAccessKey: {
          type: "string",
        },
        additionalFlags: {
          anyOf: [
            {
              default: [],
              type: "array",
              items: {
                type: "string",
                pattern: "^--[a-zA-Z0-9-]+(=[a-zA-Z0-9._:/@-]+)?$",
              },
            },
            {
              type: "null",
            },
          ],
        },
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for destination-testConnection.",
      required: ["accessKey", "additionalFlags", "bucket", "endpoint", "name", "provider", "region", "secretAccessKey"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "destination-one",
    operationId: "destination-one",
    tag: "destination",
    description: "Read Dokploy data via GET /destination.one.",
    method: "GET",
    path: "/destination.one",
    pathFields: [],
    queryFields: ["destinationId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        destinationId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for destination-one.",
      required: ["destinationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "destination-all",
    operationId: "destination-all",
    tag: "destination",
    description: "Read Dokploy data via GET /destination.all.",
    method: "GET",
    path: "/destination.all",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for destination-all.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "destination-remove",
    operationId: "destination-remove",
    tag: "destination",
    description:
      "Modify Dokploy state via POST /destination.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/destination.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["destinationId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        destinationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for destination-remove.",
      required: ["destinationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "destination-update",
    operationId: "destination-update",
    tag: "destination",
    description: "Modify Dokploy state via POST /destination.update.",
    method: "POST",
    path: "/destination.update",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "name",
      "accessKey",
      "bucket",
      "region",
      "endpoint",
      "secretAccessKey",
      "destinationId",
      "provider",
      "additionalFlags",
      "serverId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        accessKey: {
          type: "string",
        },
        bucket: {
          type: "string",
        },
        region: {
          type: "string",
        },
        endpoint: {
          type: "string",
        },
        secretAccessKey: {
          type: "string",
        },
        destinationId: {
          type: "string",
        },
        provider: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        additionalFlags: {
          anyOf: [
            {
              default: [],
              type: "array",
              items: {
                type: "string",
                pattern: "^--[a-zA-Z0-9-]+(=[a-zA-Z0-9._:/@-]+)?$",
              },
            },
            {
              type: "null",
            },
          ],
        },
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for destination-update.",
      required: [
        "accessKey",
        "additionalFlags",
        "bucket",
        "destinationId",
        "endpoint",
        "name",
        "provider",
        "region",
        "secretAccessKey",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
