// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const domainOperations: readonly DokployOperationDefinition[] = [
  {
    name: "domain-create",
    operationId: "domain-create",
    tag: "domain",
    description: "Modify Dokploy state via POST /domain.create.",
    method: "POST",
    path: "/domain.create",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "host",
      "path",
      "port",
      "customEntrypoint",
      "https",
      "applicationId",
      "certificateType",
      "customCertResolver",
      "composeId",
      "serviceName",
      "domainType",
      "previewDeploymentId",
      "internalPath",
      "stripPath",
      "middlewares",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        host: {
          type: "string",
          minLength: 1,
        },
        path: {
          anyOf: [
            {
              type: "string",
              minLength: 1,
            },
            {
              type: "null",
            },
          ],
        },
        port: {
          anyOf: [
            {
              type: "number",
              minimum: 1,
              maximum: 65535,
            },
            {
              type: "null",
            },
          ],
        },
        customEntrypoint: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        https: {
          type: "boolean",
        },
        applicationId: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        certificateType: {
          type: "string",
          enum: ["letsencrypt", "none", "custom"],
        },
        customCertResolver: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        composeId: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        serviceName: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        domainType: {
          anyOf: [
            {
              type: "string",
              enum: ["compose", "application", "preview"],
            },
            {
              type: "null",
            },
          ],
        },
        previewDeploymentId: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        internalPath: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        stripPath: {
          type: "boolean",
        },
        middlewares: {
          anyOf: [
            {
              type: "array",
              items: {
                type: "string",
              },
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for domain-create.",
      required: ["host"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "domain-byApplicationId",
    operationId: "domain-byApplicationId",
    tag: "domain",
    description: "Read Dokploy data via GET /domain.byApplicationId.",
    method: "GET",
    path: "/domain.byApplicationId",
    pathFields: [],
    queryFields: ["applicationId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        applicationId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for domain-byApplicationId.",
      required: ["applicationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "domain-byComposeId",
    operationId: "domain-byComposeId",
    tag: "domain",
    description: "Read Dokploy data via GET /domain.byComposeId.",
    method: "GET",
    path: "/domain.byComposeId",
    pathFields: [],
    queryFields: ["composeId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        composeId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for domain-byComposeId.",
      required: ["composeId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "domain-generateDomain",
    operationId: "domain-generateDomain",
    tag: "domain",
    description: "Modify Dokploy state via POST /domain.generateDomain.",
    method: "POST",
    path: "/domain.generateDomain",
    pathFields: [],
    queryFields: [],
    bodyFields: ["appName", "serverId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appName: {
          type: "string",
        },
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for domain-generateDomain.",
      required: ["appName"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "domain-canGenerateTraefikMeDomains",
    operationId: "domain-canGenerateTraefikMeDomains",
    tag: "domain",
    description: "Read Dokploy data via GET /domain.canGenerateTraefikMeDomains.",
    method: "GET",
    path: "/domain.canGenerateTraefikMeDomains",
    pathFields: [],
    queryFields: ["serverId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for domain-canGenerateTraefikMeDomains.",
      required: ["serverId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "domain-update",
    operationId: "domain-update",
    tag: "domain",
    description: "Modify Dokploy state via POST /domain.update.",
    method: "POST",
    path: "/domain.update",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "host",
      "path",
      "port",
      "customEntrypoint",
      "https",
      "certificateType",
      "customCertResolver",
      "serviceName",
      "domainType",
      "internalPath",
      "stripPath",
      "middlewares",
      "domainId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        host: {
          type: "string",
          minLength: 1,
        },
        path: {
          anyOf: [
            {
              type: "string",
              minLength: 1,
            },
            {
              type: "null",
            },
          ],
        },
        port: {
          anyOf: [
            {
              type: "number",
              minimum: 1,
              maximum: 65535,
            },
            {
              type: "null",
            },
          ],
        },
        customEntrypoint: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        https: {
          type: "boolean",
        },
        certificateType: {
          type: "string",
          enum: ["letsencrypt", "none", "custom"],
        },
        customCertResolver: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        serviceName: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        domainType: {
          anyOf: [
            {
              type: "string",
              enum: ["compose", "application", "preview"],
            },
            {
              type: "null",
            },
          ],
        },
        internalPath: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        stripPath: {
          type: "boolean",
        },
        middlewares: {
          anyOf: [
            {
              type: "array",
              items: {
                type: "string",
              },
            },
            {
              type: "null",
            },
          ],
        },
        domainId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for domain-update.",
      required: ["domainId", "host"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "domain-one",
    operationId: "domain-one",
    tag: "domain",
    description: "Read Dokploy data via GET /domain.one.",
    method: "GET",
    path: "/domain.one",
    pathFields: [],
    queryFields: ["domainId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        domainId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for domain-one.",
      required: ["domainId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "domain-delete",
    operationId: "domain-delete",
    tag: "domain",
    description:
      "Modify Dokploy state via POST /domain.delete. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/domain.delete",
    pathFields: [],
    queryFields: [],
    bodyFields: ["domainId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        domainId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for domain-delete.",
      required: ["domainId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "domain-validateDomain",
    operationId: "domain-validateDomain",
    tag: "domain",
    description: "Modify Dokploy state via POST /domain.validateDomain.",
    method: "POST",
    path: "/domain.validateDomain",
    pathFields: [],
    queryFields: [],
    bodyFields: ["domain", "serverIp"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        domain: {
          type: "string",
        },
        serverIp: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for domain-validateDomain.",
      required: ["domain"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
