// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const environmentOperations: readonly DokployOperationDefinition[] = [
  {
    name: "environment-create",
    operationId: "environment-create",
    tag: "environment",
    description: "Modify Dokploy state via POST /environment.create.",
    method: "POST",
    path: "/environment.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["name", "description", "projectId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        description: {
          type: "string",
        },
        projectId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for environment-create.",
      required: ["name", "projectId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "environment-one",
    operationId: "environment-one",
    tag: "environment",
    description: "Read Dokploy data via GET /environment.one.",
    method: "GET",
    path: "/environment.one",
    pathFields: [],
    queryFields: ["environmentId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        environmentId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for environment-one.",
      required: ["environmentId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "environment-byProjectId",
    operationId: "environment-byProjectId",
    tag: "environment",
    description: "Read Dokploy data via GET /environment.byProjectId.",
    method: "GET",
    path: "/environment.byProjectId",
    pathFields: [],
    queryFields: ["projectId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        projectId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for environment-byProjectId.",
      required: ["projectId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "environment-remove",
    operationId: "environment-remove",
    tag: "environment",
    description:
      "Modify Dokploy state via POST /environment.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/environment.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["environmentId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        environmentId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for environment-remove.",
      required: ["environmentId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "environment-update",
    operationId: "environment-update",
    tag: "environment",
    description: "Modify Dokploy state via POST /environment.update.",
    method: "POST",
    path: "/environment.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["environmentId", "name", "description", "projectId", "env"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        environmentId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
          minLength: 1,
        },
        description: {
          type: "string",
        },
        projectId: {
          type: "string",
        },
        env: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for environment-update.",
      required: ["environmentId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "environment-duplicate",
    operationId: "environment-duplicate",
    tag: "environment",
    description: "Modify Dokploy state via POST /environment.duplicate.",
    method: "POST",
    path: "/environment.duplicate",
    pathFields: [],
    queryFields: [],
    bodyFields: ["environmentId", "name", "description"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        environmentId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
          minLength: 1,
        },
        description: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for environment-duplicate.",
      required: ["environmentId", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "environment-search",
    operationId: "environment-search",
    tag: "environment",
    description: "Read Dokploy data via GET /environment.search.",
    method: "GET",
    path: "/environment.search",
    pathFields: [],
    queryFields: ["q", "name", "description", "projectId", "limit", "offset"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        q: {
          type: "string",
        },
        name: {
          type: "string",
        },
        description: {
          type: "string",
        },
        projectId: {
          type: "string",
        },
        limit: {
          default: 20,
          type: "number",
          minimum: 1,
          maximum: 100,
        },
        offset: {
          default: 0,
          type: "number",
          minimum: 0,
        },
      },
      additionalProperties: false,
      description: "Input for environment-search.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
