// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const giteaOperations: readonly DokployOperationDefinition[] = [
  {
    name: "gitea-create",
    operationId: "gitea-create",
    tag: "gitea",
    description: "Modify Dokploy state via POST /gitea.create.",
    method: "POST",
    path: "/gitea.create",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "giteaId",
      "giteaUrl",
      "giteaInternalUrl",
      "redirectUri",
      "clientId",
      "clientSecret",
      "gitProviderId",
      "accessToken",
      "refreshToken",
      "expiresAt",
      "scopes",
      "lastAuthenticatedAt",
      "name",
      "giteaUsername",
      "organizationName",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        giteaId: {
          type: "string",
        },
        giteaUrl: {
          type: "string",
          minLength: 1,
        },
        giteaInternalUrl: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        redirectUri: {
          type: "string",
        },
        clientId: {
          type: "string",
        },
        clientSecret: {
          type: "string",
        },
        gitProviderId: {
          type: "string",
        },
        accessToken: {
          type: "string",
        },
        refreshToken: {
          type: "string",
        },
        expiresAt: {
          type: "number",
        },
        scopes: {
          type: "string",
        },
        lastAuthenticatedAt: {
          type: "number",
        },
        name: {
          type: "string",
          minLength: 1,
        },
        giteaUsername: {
          type: "string",
        },
        organizationName: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for gitea-create.",
      required: ["giteaUrl", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitea-one",
    operationId: "gitea-one",
    tag: "gitea",
    description: "Read Dokploy data via GET /gitea.one.",
    method: "GET",
    path: "/gitea.one",
    pathFields: [],
    queryFields: ["giteaId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        giteaId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for gitea-one.",
      required: ["giteaId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitea-giteaProviders",
    operationId: "gitea-giteaProviders",
    tag: "gitea",
    description: "Read Dokploy data via GET /gitea.giteaProviders.",
    method: "GET",
    path: "/gitea.giteaProviders",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for gitea-giteaProviders.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitea-getGiteaRepositories",
    operationId: "gitea-getGiteaRepositories",
    tag: "gitea",
    description: "Read Dokploy data via GET /gitea.getGiteaRepositories.",
    method: "GET",
    path: "/gitea.getGiteaRepositories",
    pathFields: [],
    queryFields: ["giteaId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        giteaId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for gitea-getGiteaRepositories.",
      required: ["giteaId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitea-getGiteaBranches",
    operationId: "gitea-getGiteaBranches",
    tag: "gitea",
    description: "Read Dokploy data via GET /gitea.getGiteaBranches.",
    method: "GET",
    path: "/gitea.getGiteaBranches",
    pathFields: [],
    queryFields: ["owner", "repositoryName", "giteaId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        owner: {
          type: "string",
          minLength: 1,
        },
        repositoryName: {
          type: "string",
          minLength: 1,
        },
        giteaId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for gitea-getGiteaBranches.",
      required: ["owner", "repositoryName"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitea-testConnection",
    operationId: "gitea-testConnection",
    tag: "gitea",
    description: "Modify Dokploy state via POST /gitea.testConnection.",
    method: "POST",
    path: "/gitea.testConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["giteaId", "organizationName"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        giteaId: {
          type: "string",
        },
        organizationName: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for gitea-testConnection.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitea-update",
    operationId: "gitea-update",
    tag: "gitea",
    description: "Modify Dokploy state via POST /gitea.update.",
    method: "POST",
    path: "/gitea.update",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "giteaId",
      "giteaUrl",
      "giteaInternalUrl",
      "redirectUri",
      "clientId",
      "clientSecret",
      "gitProviderId",
      "accessToken",
      "refreshToken",
      "expiresAt",
      "scopes",
      "lastAuthenticatedAt",
      "name",
      "giteaUsername",
      "organizationName",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        giteaId: {
          type: "string",
          minLength: 1,
        },
        giteaUrl: {
          type: "string",
          minLength: 1,
        },
        giteaInternalUrl: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        redirectUri: {
          type: "string",
        },
        clientId: {
          type: "string",
        },
        clientSecret: {
          type: "string",
        },
        gitProviderId: {
          type: "string",
        },
        accessToken: {
          type: "string",
        },
        refreshToken: {
          type: "string",
        },
        expiresAt: {
          type: "number",
        },
        scopes: {
          type: "string",
        },
        lastAuthenticatedAt: {
          type: "number",
        },
        name: {
          type: "string",
          minLength: 1,
        },
        giteaUsername: {
          type: "string",
        },
        organizationName: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for gitea-update.",
      required: ["gitProviderId", "giteaId", "giteaUrl", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitea-getGiteaUrl",
    operationId: "gitea-getGiteaUrl",
    tag: "gitea",
    description: "Read Dokploy data via GET /gitea.getGiteaUrl.",
    method: "GET",
    path: "/gitea.getGiteaUrl",
    pathFields: [],
    queryFields: ["giteaId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        giteaId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for gitea-getGiteaUrl.",
      required: ["giteaId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
