// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const gitlabOperations: readonly DokployOperationDefinition[] = [
  {
    name: "gitlab-create",
    operationId: "gitlab-create",
    tag: "gitlab",
    description: "Modify Dokploy state via POST /gitlab.create.",
    method: "POST",
    path: "/gitlab.create",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "applicationId",
      "secret",
      "groupName",
      "gitProviderId",
      "redirectUri",
      "authId",
      "name",
      "gitlabUrl",
      "gitlabInternalUrl",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        applicationId: {
          type: "string",
        },
        secret: {
          type: "string",
        },
        groupName: {
          type: "string",
        },
        gitProviderId: {
          type: "string",
        },
        redirectUri: {
          type: "string",
        },
        authId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
          minLength: 1,
        },
        gitlabUrl: {
          type: "string",
          minLength: 1,
        },
        gitlabInternalUrl: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for gitlab-create.",
      required: ["authId", "gitlabUrl", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitlab-one",
    operationId: "gitlab-one",
    tag: "gitlab",
    description: "Read Dokploy data via GET /gitlab.one.",
    method: "GET",
    path: "/gitlab.one",
    pathFields: [],
    queryFields: ["gitlabId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        gitlabId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for gitlab-one.",
      required: ["gitlabId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitlab-gitlabProviders",
    operationId: "gitlab-gitlabProviders",
    tag: "gitlab",
    description: "Read Dokploy data via GET /gitlab.gitlabProviders.",
    method: "GET",
    path: "/gitlab.gitlabProviders",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for gitlab-gitlabProviders.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitlab-getGitlabRepositories",
    operationId: "gitlab-getGitlabRepositories",
    tag: "gitlab",
    description: "Read Dokploy data via GET /gitlab.getGitlabRepositories.",
    method: "GET",
    path: "/gitlab.getGitlabRepositories",
    pathFields: [],
    queryFields: ["gitlabId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        gitlabId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for gitlab-getGitlabRepositories.",
      required: ["gitlabId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitlab-getGitlabBranches",
    operationId: "gitlab-getGitlabBranches",
    tag: "gitlab",
    description: "Read Dokploy data via GET /gitlab.getGitlabBranches.",
    method: "GET",
    path: "/gitlab.getGitlabBranches",
    pathFields: [],
    queryFields: ["id", "owner", "repo", "gitlabId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "number",
        },
        owner: {
          type: "string",
        },
        repo: {
          type: "string",
        },
        gitlabId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for gitlab-getGitlabBranches.",
      required: ["owner", "repo"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitlab-testConnection",
    operationId: "gitlab-testConnection",
    tag: "gitlab",
    description: "Modify Dokploy state via POST /gitlab.testConnection.",
    method: "POST",
    path: "/gitlab.testConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["gitlabId", "groupName"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        gitlabId: {
          type: "string",
          minLength: 1,
        },
        groupName: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for gitlab-testConnection.",
      required: ["gitlabId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "gitlab-update",
    operationId: "gitlab-update",
    tag: "gitlab",
    description: "Modify Dokploy state via POST /gitlab.update.",
    method: "POST",
    path: "/gitlab.update",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "applicationId",
      "secret",
      "groupName",
      "redirectUri",
      "name",
      "gitlabId",
      "gitlabUrl",
      "gitProviderId",
      "gitlabInternalUrl",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        applicationId: {
          type: "string",
        },
        secret: {
          type: "string",
        },
        groupName: {
          type: "string",
        },
        redirectUri: {
          type: "string",
        },
        name: {
          type: "string",
          minLength: 1,
        },
        gitlabId: {
          type: "string",
          minLength: 1,
        },
        gitlabUrl: {
          type: "string",
          minLength: 1,
        },
        gitProviderId: {
          type: "string",
          minLength: 1,
        },
        gitlabInternalUrl: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for gitlab-update.",
      required: ["gitProviderId", "gitlabId", "gitlabUrl", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
