// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const notificationOperations: readonly DokployOperationDefinition[] = [
  {
    name: "notification-createSlack",
    operationId: "notification-createSlack",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createSlack.",
    method: "POST",
    path: "/notification.createSlack",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "webhookUrl",
      "channel",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
        channel: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-createSlack.",
      required: [
        "appBuildError",
        "appDeploy",
        "channel",
        "databaseBackup",
        "dockerCleanup",
        "dokployBackup",
        "dokployRestart",
        "name",
        "serverThreshold",
        "volumeBackup",
        "webhookUrl",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateSlack",
    operationId: "notification-updateSlack",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateSlack.",
    method: "POST",
    path: "/notification.updateSlack",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "webhookUrl",
      "channel",
      "notificationId",
      "slackId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
        channel: {
          type: "string",
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        slackId: {
          type: "string",
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateSlack.",
      required: ["notificationId", "slackId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testSlackConnection",
    operationId: "notification-testSlackConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testSlackConnection.",
    method: "POST",
    path: "/notification.testSlackConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["webhookUrl", "channel"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
        channel: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-testSlackConnection.",
      required: ["channel", "webhookUrl"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createTelegram",
    operationId: "notification-createTelegram",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createTelegram.",
    method: "POST",
    path: "/notification.createTelegram",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "botToken",
      "chatId",
      "messageThreadId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        botToken: {
          type: "string",
          minLength: 1,
        },
        chatId: {
          type: "string",
          minLength: 1,
        },
        messageThreadId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-createTelegram.",
      required: [
        "appBuildError",
        "appDeploy",
        "botToken",
        "chatId",
        "databaseBackup",
        "dockerCleanup",
        "dokployBackup",
        "dokployRestart",
        "messageThreadId",
        "name",
        "serverThreshold",
        "volumeBackup",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateTelegram",
    operationId: "notification-updateTelegram",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateTelegram.",
    method: "POST",
    path: "/notification.updateTelegram",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "botToken",
      "chatId",
      "messageThreadId",
      "notificationId",
      "telegramId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        botToken: {
          type: "string",
          minLength: 1,
        },
        chatId: {
          type: "string",
          minLength: 1,
        },
        messageThreadId: {
          type: "string",
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        telegramId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateTelegram.",
      required: ["notificationId", "telegramId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testTelegramConnection",
    operationId: "notification-testTelegramConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testTelegramConnection.",
    method: "POST",
    path: "/notification.testTelegramConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["botToken", "chatId", "messageThreadId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        botToken: {
          type: "string",
          minLength: 1,
        },
        chatId: {
          type: "string",
          minLength: 1,
        },
        messageThreadId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-testTelegramConnection.",
      required: ["botToken", "chatId", "messageThreadId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createDiscord",
    operationId: "notification-createDiscord",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createDiscord.",
    method: "POST",
    path: "/notification.createDiscord",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "webhookUrl",
      "decoration",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
        decoration: {
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for notification-createDiscord.",
      required: [
        "appBuildError",
        "appDeploy",
        "databaseBackup",
        "decoration",
        "dockerCleanup",
        "dokployBackup",
        "dokployRestart",
        "name",
        "serverThreshold",
        "volumeBackup",
        "webhookUrl",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateDiscord",
    operationId: "notification-updateDiscord",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateDiscord.",
    method: "POST",
    path: "/notification.updateDiscord",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "webhookUrl",
      "decoration",
      "notificationId",
      "discordId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
        decoration: {
          type: "boolean",
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        discordId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateDiscord.",
      required: ["discordId", "notificationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testDiscordConnection",
    operationId: "notification-testDiscordConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testDiscordConnection.",
    method: "POST",
    path: "/notification.testDiscordConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["webhookUrl", "decoration"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
        decoration: {
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for notification-testDiscordConnection.",
      required: ["webhookUrl"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createEmail",
    operationId: "notification-createEmail",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createEmail.",
    method: "POST",
    path: "/notification.createEmail",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "smtpServer",
      "smtpPort",
      "username",
      "password",
      "fromAddress",
      "toAddresses",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        smtpServer: {
          type: "string",
          minLength: 1,
        },
        smtpPort: {
          type: "number",
          minimum: 1,
        },
        username: {
          type: "string",
          minLength: 1,
        },
        password: {
          type: "string",
          minLength: 1,
        },
        fromAddress: {
          type: "string",
          minLength: 1,
        },
        toAddresses: {
          minItems: 1,
          type: "array",
          items: {
            type: "string",
          },
        },
      },
      additionalProperties: false,
      description: "Input for notification-createEmail.",
      required: [
        "appBuildError",
        "appDeploy",
        "databaseBackup",
        "dockerCleanup",
        "dokployBackup",
        "dokployRestart",
        "fromAddress",
        "name",
        "password",
        "serverThreshold",
        "smtpPort",
        "smtpServer",
        "toAddresses",
        "username",
        "volumeBackup",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateEmail",
    operationId: "notification-updateEmail",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateEmail.",
    method: "POST",
    path: "/notification.updateEmail",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "smtpServer",
      "smtpPort",
      "username",
      "password",
      "fromAddress",
      "toAddresses",
      "notificationId",
      "emailId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        smtpServer: {
          type: "string",
          minLength: 1,
        },
        smtpPort: {
          type: "number",
          minimum: 1,
        },
        username: {
          type: "string",
          minLength: 1,
        },
        password: {
          type: "string",
          minLength: 1,
        },
        fromAddress: {
          type: "string",
          minLength: 1,
        },
        toAddresses: {
          minItems: 1,
          type: "array",
          items: {
            type: "string",
          },
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        emailId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateEmail.",
      required: ["emailId", "notificationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testEmailConnection",
    operationId: "notification-testEmailConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testEmailConnection.",
    method: "POST",
    path: "/notification.testEmailConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["smtpServer", "smtpPort", "username", "password", "toAddresses", "fromAddress"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        smtpServer: {
          type: "string",
          minLength: 1,
        },
        smtpPort: {
          type: "number",
          minimum: 1,
        },
        username: {
          type: "string",
          minLength: 1,
        },
        password: {
          type: "string",
          minLength: 1,
        },
        toAddresses: {
          minItems: 1,
          type: "array",
          items: {
            type: "string",
          },
        },
        fromAddress: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for notification-testEmailConnection.",
      required: ["fromAddress", "password", "smtpPort", "smtpServer", "toAddresses", "username"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createResend",
    operationId: "notification-createResend",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createResend.",
    method: "POST",
    path: "/notification.createResend",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "apiKey",
      "fromAddress",
      "toAddresses",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        apiKey: {
          type: "string",
          minLength: 1,
        },
        fromAddress: {
          type: "string",
          minLength: 1,
        },
        toAddresses: {
          minItems: 1,
          type: "array",
          items: {
            type: "string",
          },
        },
      },
      additionalProperties: false,
      description: "Input for notification-createResend.",
      required: [
        "apiKey",
        "appBuildError",
        "appDeploy",
        "databaseBackup",
        "dockerCleanup",
        "dokployBackup",
        "dokployRestart",
        "fromAddress",
        "name",
        "serverThreshold",
        "toAddresses",
        "volumeBackup",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateResend",
    operationId: "notification-updateResend",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateResend.",
    method: "POST",
    path: "/notification.updateResend",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "apiKey",
      "fromAddress",
      "toAddresses",
      "notificationId",
      "resendId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        apiKey: {
          type: "string",
          minLength: 1,
        },
        fromAddress: {
          type: "string",
          minLength: 1,
        },
        toAddresses: {
          minItems: 1,
          type: "array",
          items: {
            type: "string",
          },
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        resendId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateResend.",
      required: ["notificationId", "resendId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testResendConnection",
    operationId: "notification-testResendConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testResendConnection.",
    method: "POST",
    path: "/notification.testResendConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["apiKey", "fromAddress", "toAddresses"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        apiKey: {
          type: "string",
          minLength: 1,
        },
        fromAddress: {
          type: "string",
          minLength: 1,
        },
        toAddresses: {
          minItems: 1,
          type: "array",
          items: {
            type: "string",
          },
        },
      },
      additionalProperties: false,
      description: "Input for notification-testResendConnection.",
      required: ["apiKey", "fromAddress", "toAddresses"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-remove",
    operationId: "notification-remove",
    tag: "notification",
    description:
      "Modify Dokploy state via POST /notification.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/notification.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["notificationId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        notificationId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for notification-remove.",
      required: ["notificationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-one",
    operationId: "notification-one",
    tag: "notification",
    description: "Read Dokploy data via GET /notification.one.",
    method: "GET",
    path: "/notification.one",
    pathFields: [],
    queryFields: ["notificationId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        notificationId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for notification-one.",
      required: ["notificationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-all",
    operationId: "notification-all",
    tag: "notification",
    description: "Read Dokploy data via GET /notification.all.",
    method: "GET",
    path: "/notification.all",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for notification-all.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-receiveNotification",
    operationId: "notification-receiveNotification",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.receiveNotification.",
    method: "POST",
    path: "/notification.receiveNotification",
    pathFields: [],
    queryFields: [],
    bodyFields: ["ServerType", "Type", "Value", "Threshold", "Message", "Timestamp", "Token"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        ServerType: {
          default: "Dokploy",
          type: "string",
          enum: ["Dokploy", "Remote"],
        },
        Type: {
          type: "string",
          enum: ["Memory", "CPU"],
        },
        Value: {
          type: "number",
        },
        Threshold: {
          type: "number",
        },
        Message: {
          type: "string",
        },
        Timestamp: {
          type: "string",
        },
        Token: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-receiveNotification.",
      required: ["Message", "Threshold", "Timestamp", "Token", "Type", "Value"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createGotify",
    operationId: "notification-createGotify",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createGotify.",
    method: "POST",
    path: "/notification.createGotify",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverUrl",
      "appToken",
      "priority",
      "decoration",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverUrl: {
          type: "string",
          minLength: 1,
        },
        appToken: {
          type: "string",
          minLength: 1,
        },
        priority: {
          type: "number",
          minimum: 1,
        },
        decoration: {
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for notification-createGotify.",
      required: [
        "appBuildError",
        "appDeploy",
        "appToken",
        "databaseBackup",
        "decoration",
        "dockerCleanup",
        "dokployBackup",
        "dokployRestart",
        "name",
        "priority",
        "serverUrl",
        "volumeBackup",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateGotify",
    operationId: "notification-updateGotify",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateGotify.",
    method: "POST",
    path: "/notification.updateGotify",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverUrl",
      "appToken",
      "priority",
      "decoration",
      "notificationId",
      "gotifyId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverUrl: {
          type: "string",
          minLength: 1,
        },
        appToken: {
          type: "string",
          minLength: 1,
        },
        priority: {
          type: "number",
          minimum: 1,
        },
        decoration: {
          type: "boolean",
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        gotifyId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateGotify.",
      required: ["gotifyId", "notificationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testGotifyConnection",
    operationId: "notification-testGotifyConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testGotifyConnection.",
    method: "POST",
    path: "/notification.testGotifyConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["serverUrl", "appToken", "priority", "decoration"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        serverUrl: {
          type: "string",
          minLength: 1,
        },
        appToken: {
          type: "string",
          minLength: 1,
        },
        priority: {
          type: "number",
          minimum: 1,
        },
        decoration: {
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for notification-testGotifyConnection.",
      required: ["appToken", "priority", "serverUrl"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createNtfy",
    operationId: "notification-createNtfy",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createNtfy.",
    method: "POST",
    path: "/notification.createNtfy",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverUrl",
      "topic",
      "accessToken",
      "priority",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverUrl: {
          type: "string",
          minLength: 1,
        },
        topic: {
          type: "string",
          minLength: 1,
        },
        accessToken: {
          type: "string",
        },
        priority: {
          type: "number",
          minimum: 1,
        },
      },
      additionalProperties: false,
      description: "Input for notification-createNtfy.",
      required: [
        "accessToken",
        "appBuildError",
        "appDeploy",
        "databaseBackup",
        "dockerCleanup",
        "dokployBackup",
        "dokployRestart",
        "name",
        "priority",
        "serverUrl",
        "topic",
        "volumeBackup",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateNtfy",
    operationId: "notification-updateNtfy",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateNtfy.",
    method: "POST",
    path: "/notification.updateNtfy",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverUrl",
      "topic",
      "accessToken",
      "priority",
      "notificationId",
      "ntfyId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverUrl: {
          type: "string",
          minLength: 1,
        },
        topic: {
          type: "string",
          minLength: 1,
        },
        accessToken: {
          type: "string",
        },
        priority: {
          type: "number",
          minimum: 1,
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        ntfyId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateNtfy.",
      required: ["notificationId", "ntfyId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testNtfyConnection",
    operationId: "notification-testNtfyConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testNtfyConnection.",
    method: "POST",
    path: "/notification.testNtfyConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["serverUrl", "topic", "accessToken", "priority"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        serverUrl: {
          type: "string",
          minLength: 1,
        },
        topic: {
          type: "string",
          minLength: 1,
        },
        accessToken: {
          type: "string",
        },
        priority: {
          type: "number",
          minimum: 1,
        },
      },
      additionalProperties: false,
      description: "Input for notification-testNtfyConnection.",
      required: ["accessToken", "priority", "serverUrl", "topic"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createMattermost",
    operationId: "notification-createMattermost",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createMattermost.",
    method: "POST",
    path: "/notification.createMattermost",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "webhookUrl",
      "channel",
      "username",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        webhookUrl: {
          type: "string",
          format: "uri",
        },
        channel: {
          type: "string",
        },
        username: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-createMattermost.",
      required: [
        "appBuildError",
        "appDeploy",
        "databaseBackup",
        "dockerCleanup",
        "dokployBackup",
        "dokployRestart",
        "name",
        "serverThreshold",
        "volumeBackup",
        "webhookUrl",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateMattermost",
    operationId: "notification-updateMattermost",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateMattermost.",
    method: "POST",
    path: "/notification.updateMattermost",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "webhookUrl",
      "channel",
      "username",
      "notificationId",
      "mattermostId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        webhookUrl: {
          type: "string",
          format: "uri",
        },
        channel: {
          type: "string",
        },
        username: {
          type: "string",
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        mattermostId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateMattermost.",
      required: ["mattermostId", "notificationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testMattermostConnection",
    operationId: "notification-testMattermostConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testMattermostConnection.",
    method: "POST",
    path: "/notification.testMattermostConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["webhookUrl", "channel", "username"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        webhookUrl: {
          type: "string",
          format: "uri",
        },
        channel: {
          type: "string",
        },
        username: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-testMattermostConnection.",
      required: ["webhookUrl"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createCustom",
    operationId: "notification-createCustom",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createCustom.",
    method: "POST",
    path: "/notification.createCustom",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "endpoint",
      "headers",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        endpoint: {
          type: "string",
          minLength: 1,
        },
        headers: {
          type: "object",
          propertyNames: {
            type: "string",
          },
          additionalProperties: {
            type: "string",
          },
        },
      },
      additionalProperties: false,
      description: "Input for notification-createCustom.",
      required: ["endpoint", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateCustom",
    operationId: "notification-updateCustom",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateCustom.",
    method: "POST",
    path: "/notification.updateCustom",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "endpoint",
      "headers",
      "notificationId",
      "customId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        endpoint: {
          type: "string",
          minLength: 1,
        },
        headers: {
          type: "object",
          propertyNames: {
            type: "string",
          },
          additionalProperties: {
            type: "string",
          },
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        customId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateCustom.",
      required: ["customId", "notificationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testCustomConnection",
    operationId: "notification-testCustomConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testCustomConnection.",
    method: "POST",
    path: "/notification.testCustomConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["endpoint", "headers"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        endpoint: {
          type: "string",
          minLength: 1,
        },
        headers: {
          type: "object",
          propertyNames: {
            type: "string",
          },
          additionalProperties: {
            type: "string",
          },
        },
      },
      additionalProperties: false,
      description: "Input for notification-testCustomConnection.",
      required: ["endpoint"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createLark",
    operationId: "notification-createLark",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createLark.",
    method: "POST",
    path: "/notification.createLark",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "webhookUrl",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for notification-createLark.",
      required: [
        "appBuildError",
        "appDeploy",
        "databaseBackup",
        "dockerCleanup",
        "dokployBackup",
        "dokployRestart",
        "name",
        "serverThreshold",
        "volumeBackup",
        "webhookUrl",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateLark",
    operationId: "notification-updateLark",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateLark.",
    method: "POST",
    path: "/notification.updateLark",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "webhookUrl",
      "notificationId",
      "larkId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        larkId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateLark.",
      required: ["larkId", "notificationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testLarkConnection",
    operationId: "notification-testLarkConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testLarkConnection.",
    method: "POST",
    path: "/notification.testLarkConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["webhookUrl"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for notification-testLarkConnection.",
      required: ["webhookUrl"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createTeams",
    operationId: "notification-createTeams",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createTeams.",
    method: "POST",
    path: "/notification.createTeams",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "webhookUrl",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for notification-createTeams.",
      required: [
        "appBuildError",
        "appDeploy",
        "databaseBackup",
        "dockerCleanup",
        "dokployBackup",
        "dokployRestart",
        "name",
        "serverThreshold",
        "volumeBackup",
        "webhookUrl",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updateTeams",
    operationId: "notification-updateTeams",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updateTeams.",
    method: "POST",
    path: "/notification.updateTeams",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "webhookUrl",
      "notificationId",
      "teamsId",
      "organizationId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
        teamsId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updateTeams.",
      required: ["notificationId", "teamsId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testTeamsConnection",
    operationId: "notification-testTeamsConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testTeamsConnection.",
    method: "POST",
    path: "/notification.testTeamsConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["webhookUrl"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        webhookUrl: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for notification-testTeamsConnection.",
      required: ["webhookUrl"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-createPushover",
    operationId: "notification-createPushover",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.createPushover.",
    method: "POST",
    path: "/notification.createPushover",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
      "userKey",
      "apiToken",
      "priority",
      "retry",
      "expire",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
        userKey: {
          type: "string",
          minLength: 1,
        },
        apiToken: {
          type: "string",
          minLength: 1,
        },
        priority: {
          default: 0,
          type: "number",
          minimum: -2,
          maximum: 2,
        },
        retry: {
          anyOf: [
            {
              type: "number",
              minimum: 30,
            },
            {
              type: "null",
            },
          ],
        },
        expire: {
          anyOf: [
            {
              type: "number",
              minimum: 1,
              maximum: 10800,
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for notification-createPushover.",
      required: ["apiToken", "name", "userKey"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-updatePushover",
    operationId: "notification-updatePushover",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.updatePushover.",
    method: "POST",
    path: "/notification.updatePushover",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "notificationId",
      "pushoverId",
      "organizationId",
      "userKey",
      "apiToken",
      "priority",
      "retry",
      "expire",
      "appBuildError",
      "databaseBackup",
      "dokployBackup",
      "volumeBackup",
      "dokployRestart",
      "name",
      "appDeploy",
      "dockerCleanup",
      "serverThreshold",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        notificationId: {
          type: "string",
          minLength: 1,
        },
        pushoverId: {
          type: "string",
          minLength: 1,
        },
        organizationId: {
          type: "string",
        },
        userKey: {
          type: "string",
          minLength: 1,
        },
        apiToken: {
          type: "string",
          minLength: 1,
        },
        priority: {
          type: "number",
          minimum: -2,
          maximum: 2,
        },
        retry: {
          anyOf: [
            {
              type: "number",
              minimum: 30,
            },
            {
              type: "null",
            },
          ],
        },
        expire: {
          anyOf: [
            {
              type: "number",
              minimum: 1,
              maximum: 10800,
            },
            {
              type: "null",
            },
          ],
        },
        appBuildError: {
          type: "boolean",
        },
        databaseBackup: {
          type: "boolean",
        },
        dokployBackup: {
          type: "boolean",
        },
        volumeBackup: {
          type: "boolean",
        },
        dokployRestart: {
          type: "boolean",
        },
        name: {
          type: "string",
        },
        appDeploy: {
          type: "boolean",
        },
        dockerCleanup: {
          type: "boolean",
        },
        serverThreshold: {
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for notification-updatePushover.",
      required: ["notificationId", "pushoverId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-testPushoverConnection",
    operationId: "notification-testPushoverConnection",
    tag: "notification",
    description: "Modify Dokploy state via POST /notification.testPushoverConnection.",
    method: "POST",
    path: "/notification.testPushoverConnection",
    pathFields: [],
    queryFields: [],
    bodyFields: ["userKey", "apiToken", "priority", "retry", "expire"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        userKey: {
          type: "string",
          minLength: 1,
        },
        apiToken: {
          type: "string",
          minLength: 1,
        },
        priority: {
          type: "number",
          minimum: -2,
          maximum: 2,
        },
        retry: {
          anyOf: [
            {
              type: "number",
              minimum: 30,
            },
            {
              type: "null",
            },
          ],
        },
        expire: {
          anyOf: [
            {
              type: "number",
              minimum: 1,
              maximum: 10800,
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for notification-testPushoverConnection.",
      required: ["apiToken", "priority", "userKey"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "notification-getEmailProviders",
    operationId: "notification-getEmailProviders",
    tag: "notification",
    description: "Read Dokploy data via GET /notification.getEmailProviders.",
    method: "GET",
    path: "/notification.getEmailProviders",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for notification-getEmailProviders.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
