// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const patchOperations: readonly DokployOperationDefinition[] = [
  {
    name: "patch-create",
    operationId: "patch-create",
    tag: "patch",
    description: "Modify Dokploy state via POST /patch.create.",
    method: "POST",
    path: "/patch.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["filePath", "content", "type", "enabled", "applicationId", "composeId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        filePath: {
          type: "string",
          minLength: 1,
        },
        content: {
          type: "string",
        },
        type: {
          type: "string",
          enum: ["create", "update", "delete"],
        },
        enabled: {
          type: "boolean",
        },
        applicationId: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        composeId: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for patch-create.",
      required: ["content", "filePath"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-one",
    operationId: "patch-one",
    tag: "patch",
    description: "Read Dokploy data via GET /patch.one.",
    method: "GET",
    path: "/patch.one",
    pathFields: [],
    queryFields: ["patchId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        patchId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for patch-one.",
      required: ["patchId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-byEntityId",
    operationId: "patch-byEntityId",
    tag: "patch",
    description: "Read Dokploy data via GET /patch.byEntityId.",
    method: "GET",
    path: "/patch.byEntityId",
    pathFields: [],
    queryFields: ["id", "type"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
        },
        type: {
          type: "string",
          enum: ["application", "compose"],
        },
      },
      additionalProperties: false,
      description: "Input for patch-byEntityId.",
      required: ["id", "type"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-update",
    operationId: "patch-update",
    tag: "patch",
    description: "Modify Dokploy state via POST /patch.update.",
    method: "POST",
    path: "/patch.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["patchId", "type", "filePath", "enabled", "content", "createdAt", "updatedAt"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        patchId: {
          type: "string",
          minLength: 1,
        },
        type: {
          type: "string",
          enum: ["create", "update", "delete"],
        },
        filePath: {
          type: "string",
          minLength: 1,
        },
        enabled: {
          type: "boolean",
        },
        content: {
          type: "string",
        },
        createdAt: {
          type: "string",
        },
        updatedAt: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for patch-update.",
      required: ["patchId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-delete",
    operationId: "patch-delete",
    tag: "patch",
    description:
      "Modify Dokploy state via POST /patch.delete. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/patch.delete",
    pathFields: [],
    queryFields: [],
    bodyFields: ["patchId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        patchId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for patch-delete.",
      required: ["patchId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-toggleEnabled",
    operationId: "patch-toggleEnabled",
    tag: "patch",
    description: "Modify Dokploy state via POST /patch.toggleEnabled.",
    method: "POST",
    path: "/patch.toggleEnabled",
    pathFields: [],
    queryFields: [],
    bodyFields: ["patchId", "enabled"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        patchId: {
          type: "string",
          minLength: 1,
        },
        enabled: {
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for patch-toggleEnabled.",
      required: ["enabled", "patchId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-ensureRepo",
    operationId: "patch-ensureRepo",
    tag: "patch",
    description: "Modify Dokploy state via POST /patch.ensureRepo.",
    method: "POST",
    path: "/patch.ensureRepo",
    pathFields: [],
    queryFields: [],
    bodyFields: ["id", "type"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
        },
        type: {
          type: "string",
          enum: ["application", "compose"],
        },
      },
      additionalProperties: false,
      description: "Input for patch-ensureRepo.",
      required: ["id", "type"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-readRepoDirectories",
    operationId: "patch-readRepoDirectories",
    tag: "patch",
    description: "Read Dokploy data via GET /patch.readRepoDirectories.",
    method: "GET",
    path: "/patch.readRepoDirectories",
    pathFields: [],
    queryFields: ["id", "type", "repoPath"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
          minLength: 1,
        },
        type: {
          type: "string",
          enum: ["application", "compose"],
        },
        repoPath: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for patch-readRepoDirectories.",
      required: ["id", "repoPath", "type"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-readRepoFile",
    operationId: "patch-readRepoFile",
    tag: "patch",
    description: "Read Dokploy data via GET /patch.readRepoFile.",
    method: "GET",
    path: "/patch.readRepoFile",
    pathFields: [],
    queryFields: ["id", "type", "filePath"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
          minLength: 1,
        },
        type: {
          type: "string",
          enum: ["application", "compose"],
        },
        filePath: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for patch-readRepoFile.",
      required: ["filePath", "id", "type"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-saveFileAsPatch",
    operationId: "patch-saveFileAsPatch",
    tag: "patch",
    description: "Modify Dokploy state via POST /patch.saveFileAsPatch.",
    method: "POST",
    path: "/patch.saveFileAsPatch",
    pathFields: [],
    queryFields: [],
    bodyFields: ["id", "type", "filePath", "content", "patchType"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
          minLength: 1,
        },
        type: {
          type: "string",
          enum: ["application", "compose"],
        },
        filePath: {
          type: "string",
        },
        content: {
          type: "string",
        },
        patchType: {
          default: "update",
          type: "string",
          enum: ["create", "update"],
        },
      },
      additionalProperties: false,
      description: "Input for patch-saveFileAsPatch.",
      required: ["content", "filePath", "id", "type"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-markFileForDeletion",
    operationId: "patch-markFileForDeletion",
    tag: "patch",
    description: "Modify Dokploy state via POST /patch.markFileForDeletion.",
    method: "POST",
    path: "/patch.markFileForDeletion",
    pathFields: [],
    queryFields: [],
    bodyFields: ["id", "type", "filePath"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
          minLength: 1,
        },
        type: {
          type: "string",
          enum: ["application", "compose"],
        },
        filePath: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for patch-markFileForDeletion.",
      required: ["filePath", "id", "type"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "patch-cleanPatchRepos",
    operationId: "patch-cleanPatchRepos",
    tag: "patch",
    description:
      "Modify Dokploy state via POST /patch.cleanPatchRepos. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/patch.cleanPatchRepos",
    pathFields: [],
    queryFields: [],
    bodyFields: ["serverId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for patch-cleanPatchRepos.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
