// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const portOperations: readonly DokployOperationDefinition[] = [
  {
    name: "port-create",
    operationId: "port-create",
    tag: "port",
    description: "Modify Dokploy state via POST /port.create.",
    method: "POST",
    path: "/port.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["publishedPort", "publishMode", "targetPort", "protocol", "applicationId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        publishedPort: {
          type: "number",
        },
        publishMode: {
          default: "ingress",
          type: "string",
          enum: ["ingress", "host"],
        },
        targetPort: {
          type: "number",
        },
        protocol: {
          default: "tcp",
          type: "string",
          enum: ["tcp", "udp"],
        },
        applicationId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for port-create.",
      required: ["applicationId", "protocol", "publishMode", "publishedPort", "targetPort"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "port-one",
    operationId: "port-one",
    tag: "port",
    description: "Read Dokploy data via GET /port.one.",
    method: "GET",
    path: "/port.one",
    pathFields: [],
    queryFields: ["portId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        portId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for port-one.",
      required: ["portId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "port-delete",
    operationId: "port-delete",
    tag: "port",
    description:
      "Modify Dokploy state via POST /port.delete. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/port.delete",
    pathFields: [],
    queryFields: [],
    bodyFields: ["portId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        portId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for port-delete.",
      required: ["portId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "port-update",
    operationId: "port-update",
    tag: "port",
    description: "Modify Dokploy state via POST /port.update.",
    method: "POST",
    path: "/port.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["portId", "publishedPort", "publishMode", "targetPort", "protocol"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        portId: {
          type: "string",
          minLength: 1,
        },
        publishedPort: {
          type: "number",
        },
        publishMode: {
          default: "ingress",
          type: "string",
          enum: ["ingress", "host"],
        },
        targetPort: {
          type: "number",
        },
        protocol: {
          default: "tcp",
          type: "string",
          enum: ["tcp", "udp"],
        },
      },
      additionalProperties: false,
      description: "Input for port-update.",
      required: ["portId", "protocol", "publishMode", "publishedPort", "targetPort"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
