// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const postgresOperations: readonly DokployOperationDefinition[] = [
  {
    name: "postgres-create",
    operationId: "postgres-create",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.create.",
    method: "POST",
    path: "/postgres.create",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "name",
      "appName",
      "databaseName",
      "databaseUser",
      "databasePassword",
      "dockerImage",
      "environmentId",
      "description",
      "serverId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        appName: {
          type: "string",
          minLength: 1,
          maxLength: 63,
          pattern: "^[a-zA-Z0-9._-]+$",
        },
        databaseName: {
          type: "string",
          minLength: 1,
        },
        databaseUser: {
          type: "string",
          minLength: 1,
        },
        databasePassword: {
          type: "string",
          pattern: "^[a-zA-Z0-9@#%^&*()_+\\-=[\\]{}|;:,.<>?~`]*$",
        },
        dockerImage: {
          default: "postgres:18",
          type: "string",
        },
        environmentId: {
          type: "string",
        },
        description: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        serverId: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for postgres-create.",
      required: ["databaseName", "databasePassword", "databaseUser", "environmentId", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-one",
    operationId: "postgres-one",
    tag: "postgres",
    description: "Read Dokploy data via GET /postgres.one.",
    method: "GET",
    path: "/postgres.one",
    pathFields: [],
    queryFields: ["postgresId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for postgres-one.",
      required: ["postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-start",
    operationId: "postgres-start",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.start.",
    method: "POST",
    path: "/postgres.start",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for postgres-start.",
      required: ["postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-stop",
    operationId: "postgres-stop",
    tag: "postgres",
    description:
      "Modify Dokploy state via POST /postgres.stop. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/postgres.stop",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for postgres-stop.",
      required: ["postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-saveExternalPort",
    operationId: "postgres-saveExternalPort",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.saveExternalPort.",
    method: "POST",
    path: "/postgres.saveExternalPort",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId", "externalPort"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
        },
        externalPort: {
          anyOf: [
            {
              type: "number",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for postgres-saveExternalPort.",
      required: ["externalPort", "postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-deploy",
    operationId: "postgres-deploy",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.deploy.",
    method: "POST",
    path: "/postgres.deploy",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for postgres-deploy.",
      required: ["postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-changeStatus",
    operationId: "postgres-changeStatus",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.changeStatus.",
    method: "POST",
    path: "/postgres.changeStatus",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId", "applicationStatus"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
        },
        applicationStatus: {
          type: "string",
          enum: ["idle", "running", "done", "error"],
        },
      },
      additionalProperties: false,
      description: "Input for postgres-changeStatus.",
      required: ["applicationStatus", "postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-remove",
    operationId: "postgres-remove",
    tag: "postgres",
    description:
      "Modify Dokploy state via POST /postgres.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/postgres.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for postgres-remove.",
      required: ["postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-saveEnvironment",
    operationId: "postgres-saveEnvironment",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.saveEnvironment.",
    method: "POST",
    path: "/postgres.saveEnvironment",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId", "env"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
        },
        env: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for postgres-saveEnvironment.",
      required: ["env", "postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-reload",
    operationId: "postgres-reload",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.reload.",
    method: "POST",
    path: "/postgres.reload",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId", "appName"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
        },
        appName: {
          type: "string",
          minLength: 1,
          maxLength: 63,
          pattern: "^[a-zA-Z0-9._-]+$",
        },
      },
      additionalProperties: false,
      description: "Input for postgres-reload.",
      required: ["appName", "postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-update",
    operationId: "postgres-update",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.update.",
    method: "POST",
    path: "/postgres.update",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "postgresId",
      "name",
      "appName",
      "databaseName",
      "databaseUser",
      "databasePassword",
      "description",
      "dockerImage",
      "command",
      "args",
      "env",
      "memoryReservation",
      "externalPort",
      "memoryLimit",
      "cpuReservation",
      "cpuLimit",
      "applicationStatus",
      "healthCheckSwarm",
      "restartPolicySwarm",
      "placementSwarm",
      "updateConfigSwarm",
      "rollbackConfigSwarm",
      "modeSwarm",
      "labelsSwarm",
      "networkSwarm",
      "stopGracePeriodSwarm",
      "endpointSpecSwarm",
      "ulimitsSwarm",
      "replicas",
      "createdAt",
      "environmentId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
          minLength: 1,
        },
        appName: {
          type: "string",
          minLength: 1,
          maxLength: 63,
          pattern: "^[a-zA-Z0-9._-]+$",
        },
        databaseName: {
          type: "string",
          minLength: 1,
        },
        databaseUser: {
          type: "string",
          minLength: 1,
        },
        databasePassword: {
          type: "string",
          pattern: "^[a-zA-Z0-9@#%^&*()_+\\-=[\\]{}|;:,.<>?~`]*$",
        },
        description: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        dockerImage: {
          type: "string",
        },
        command: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        args: {
          anyOf: [
            {
              type: "array",
              items: {
                type: "string",
              },
            },
            {
              type: "null",
            },
          ],
        },
        env: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        memoryReservation: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        externalPort: {
          anyOf: [
            {
              type: "number",
            },
            {
              type: "null",
            },
          ],
        },
        memoryLimit: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        cpuReservation: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        cpuLimit: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        applicationStatus: {
          type: "string",
          enum: ["idle", "running", "done", "error"],
        },
        healthCheckSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Test: {
                      type: "array",
                      items: {
                        type: "string",
                      },
                    },
                    Interval: {
                      type: "number",
                    },
                    Timeout: {
                      type: "number",
                    },
                    StartPeriod: {
                      type: "number",
                    },
                    Retries: {
                      type: "number",
                    },
                  },
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        restartPolicySwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Condition: {
                      type: "string",
                    },
                    Delay: {
                      type: "number",
                    },
                    MaxAttempts: {
                      type: "number",
                    },
                    Window: {
                      type: "number",
                    },
                  },
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        placementSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Constraints: {
                      type: "array",
                      items: {
                        type: "string",
                      },
                    },
                    Preferences: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          Spread: {
                            type: "object",
                            properties: {
                              SpreadDescriptor: {
                                type: "string",
                              },
                            },
                            required: ["SpreadDescriptor"],
                          },
                        },
                        required: ["Spread"],
                        additionalProperties: false,
                      },
                    },
                    MaxReplicas: {
                      type: "number",
                    },
                    Platforms: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          Architecture: {
                            type: "string",
                          },
                          OS: {
                            type: "string",
                          },
                        },
                        required: ["Architecture", "OS"],
                        additionalProperties: false,
                      },
                    },
                  },
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        updateConfigSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Parallelism: {
                      type: "number",
                    },
                    Delay: {
                      type: "number",
                    },
                    FailureAction: {
                      type: "string",
                    },
                    Monitor: {
                      type: "number",
                    },
                    MaxFailureRatio: {
                      type: "number",
                    },
                    Order: {
                      type: "string",
                    },
                  },
                  required: ["Parallelism", "Order"],
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        rollbackConfigSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Parallelism: {
                      type: "number",
                    },
                    Delay: {
                      type: "number",
                    },
                    FailureAction: {
                      type: "string",
                    },
                    Monitor: {
                      type: "number",
                    },
                    MaxFailureRatio: {
                      type: "number",
                    },
                    Order: {
                      type: "string",
                    },
                  },
                  required: ["Parallelism", "Order"],
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        modeSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Replicated: {
                      type: "object",
                      properties: {
                        Replicas: {
                          type: "number",
                        },
                      },
                      additionalProperties: false,
                    },
                    Global: {
                      type: "object",
                      properties: {},
                    },
                    ReplicatedJob: {
                      type: "object",
                      properties: {
                        MaxConcurrent: {
                          type: "number",
                        },
                        TotalCompletions: {
                          type: "number",
                        },
                      },
                      additionalProperties: false,
                    },
                    GlobalJob: {
                      type: "object",
                      properties: {},
                    },
                  },
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        labelsSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  propertyNames: {
                    type: "string",
                  },
                  additionalProperties: {
                    type: "string",
                  },
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        networkSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      Target: {
                        type: "string",
                      },
                      Aliases: {
                        type: "array",
                        items: {
                          type: "string",
                        },
                      },
                      DriverOpts: {
                        type: "object",
                        propertyNames: {
                          type: "string",
                        },
                        additionalProperties: {
                          type: "string",
                        },
                      },
                    },
                    additionalProperties: false,
                  },
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        stopGracePeriodSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "number",
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        endpointSpecSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Mode: {
                      type: "string",
                    },
                    Ports: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          Protocol: {
                            type: "string",
                          },
                          TargetPort: {
                            type: "number",
                          },
                          PublishedPort: {
                            type: "number",
                          },
                          PublishMode: {
                            type: "string",
                          },
                        },
                        additionalProperties: false,
                      },
                    },
                  },
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        ulimitsSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      Name: {
                        type: "string",
                        minLength: 1,
                      },
                      Soft: {
                        type: "integer",
                        minimum: -1,
                        maximum: 9007199254740991,
                      },
                      Hard: {
                        type: "integer",
                        minimum: -1,
                        maximum: 9007199254740991,
                      },
                    },
                    required: ["Name", "Soft", "Hard"],
                    additionalProperties: false,
                  },
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        replicas: {
          type: "number",
        },
        createdAt: {
          type: "string",
        },
        environmentId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for postgres-update.",
      required: ["postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-changePassword",
    operationId: "postgres-changePassword",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.changePassword.",
    method: "POST",
    path: "/postgres.changePassword",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId", "password"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
          minLength: 1,
        },
        password: {
          type: "string",
          minLength: 1,
          pattern: "^[a-zA-Z0-9@#%^&*()_+\\-=[\\]{}|;:,.<>?~`]*$",
        },
      },
      additionalProperties: false,
      description: "Input for postgres-changePassword.",
      required: ["password", "postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-move",
    operationId: "postgres-move",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.move.",
    method: "POST",
    path: "/postgres.move",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId", "targetEnvironmentId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
        },
        targetEnvironmentId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for postgres-move.",
      required: ["postgresId", "targetEnvironmentId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-rebuild",
    operationId: "postgres-rebuild",
    tag: "postgres",
    description: "Modify Dokploy state via POST /postgres.rebuild.",
    method: "POST",
    path: "/postgres.rebuild",
    pathFields: [],
    queryFields: [],
    bodyFields: ["postgresId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for postgres-rebuild.",
      required: ["postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-search",
    operationId: "postgres-search",
    tag: "postgres",
    description: "Read Dokploy data via GET /postgres.search.",
    method: "GET",
    path: "/postgres.search",
    pathFields: [],
    queryFields: ["q", "name", "appName", "description", "projectId", "environmentId", "limit", "offset"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        q: {
          type: "string",
        },
        name: {
          type: "string",
        },
        appName: {
          type: "string",
        },
        description: {
          type: "string",
        },
        projectId: {
          type: "string",
        },
        environmentId: {
          type: "string",
        },
        limit: {
          default: 20,
          type: "number",
          minimum: 1,
          maximum: 100,
        },
        offset: {
          default: 0,
          type: "number",
          minimum: 0,
        },
      },
      additionalProperties: false,
      description: "Input for postgres-search.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "postgres-readLogs",
    operationId: "postgres-readLogs",
    tag: "postgres",
    description: "Read Dokploy data via GET /postgres.readLogs.",
    method: "GET",
    path: "/postgres.readLogs",
    pathFields: [],
    queryFields: ["postgresId", "tail", "since", "search"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        postgresId: {
          type: "string",
          minLength: 1,
        },
        tail: {
          default: 100,
          type: "integer",
          minimum: 1,
          maximum: 10000,
        },
        since: {
          default: "all",
          type: "string",
          pattern: "^(all|\\d+[smhd])$",
        },
        search: {
          type: "string",
          pattern: "^[a-zA-Z0-9 ._-]{0,500}$",
        },
      },
      additionalProperties: false,
      description: "Input for postgres-readLogs.",
      required: ["postgresId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
