// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const projectOperations: readonly DokployOperationDefinition[] = [
  {
    name: "project-create",
    operationId: "project-create",
    tag: "project",
    description: "Modify Dokploy state via POST /project.create.",
    method: "POST",
    path: "/project.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["name", "description", "env"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        description: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        env: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for project-create.",
      required: ["name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "project-one",
    operationId: "project-one",
    tag: "project",
    description: "Read Dokploy data via GET /project.one.",
    method: "GET",
    path: "/project.one",
    pathFields: [],
    queryFields: ["projectId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        projectId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for project-one.",
      required: ["projectId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "project-all",
    operationId: "project-all",
    tag: "project",
    description: "Read Dokploy data via GET /project.all.",
    method: "GET",
    path: "/project.all",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for project-all.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "project-allForPermissions",
    operationId: "project-allForPermissions",
    tag: "project",
    description: "Read Dokploy data via GET /project.allForPermissions.",
    method: "GET",
    path: "/project.allForPermissions",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for project-allForPermissions.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "project-homeStats",
    operationId: "project-homeStats",
    tag: "project",
    description: "Read Dokploy data via GET /project.homeStats.",
    method: "GET",
    path: "/project.homeStats",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for project-homeStats.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "project-search",
    operationId: "project-search",
    tag: "project",
    description: "Read Dokploy data via GET /project.search.",
    method: "GET",
    path: "/project.search",
    pathFields: [],
    queryFields: ["q", "name", "description", "limit", "offset"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        q: {
          type: "string",
        },
        name: {
          type: "string",
        },
        description: {
          type: "string",
        },
        limit: {
          default: 20,
          type: "number",
          minimum: 1,
          maximum: 100,
        },
        offset: {
          default: 0,
          type: "number",
          minimum: 0,
        },
      },
      additionalProperties: false,
      description: "Input for project-search.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "project-remove",
    operationId: "project-remove",
    tag: "project",
    description:
      "Modify Dokploy state via POST /project.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/project.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["projectId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        projectId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for project-remove.",
      required: ["projectId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "project-update",
    operationId: "project-update",
    tag: "project",
    description: "Modify Dokploy state via POST /project.update.",
    method: "POST",
    path: "/project.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["projectId", "name", "description", "createdAt", "organizationId", "env"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        projectId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
          minLength: 1,
        },
        description: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        createdAt: {
          type: "string",
        },
        organizationId: {
          type: "string",
        },
        env: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for project-update.",
      required: ["projectId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "project-duplicate",
    operationId: "project-duplicate",
    tag: "project",
    description: "Modify Dokploy state via POST /project.duplicate.",
    method: "POST",
    path: "/project.duplicate",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "sourceEnvironmentId",
      "name",
      "description",
      "includeServices",
      "selectedServices",
      "duplicateInSameProject",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        sourceEnvironmentId: {
          type: "string",
        },
        name: {
          type: "string",
        },
        description: {
          type: "string",
        },
        includeServices: {
          default: true,
          type: "boolean",
        },
        selectedServices: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: {
                type: "string",
              },
              type: {
                type: "string",
                enum: ["application", "compose", "libsql", "mariadb", "mongo", "mysql", "postgres", "redis"],
              },
            },
            required: ["id", "type"],
          },
        },
        duplicateInSameProject: {
          default: false,
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for project-duplicate.",
      required: ["name", "sourceEnvironmentId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
