// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const redisOperations: readonly DokployOperationDefinition[] = [
  {
    name: "redis-create",
    operationId: "redis-create",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.create.",
    method: "POST",
    path: "/redis.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["name", "appName", "databasePassword", "dockerImage", "environmentId", "description", "serverId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        appName: {
          type: "string",
          minLength: 1,
          maxLength: 63,
          pattern: "^[a-zA-Z0-9._-]+$",
        },
        databasePassword: {
          type: "string",
        },
        dockerImage: {
          default: "redis:8",
          type: "string",
        },
        environmentId: {
          type: "string",
        },
        description: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        serverId: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for redis-create.",
      required: ["databasePassword", "environmentId", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-one",
    operationId: "redis-one",
    tag: "redis",
    description: "Read Dokploy data via GET /redis.one.",
    method: "GET",
    path: "/redis.one",
    pathFields: [],
    queryFields: ["redisId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for redis-one.",
      required: ["redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-start",
    operationId: "redis-start",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.start.",
    method: "POST",
    path: "/redis.start",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for redis-start.",
      required: ["redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-reload",
    operationId: "redis-reload",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.reload.",
    method: "POST",
    path: "/redis.reload",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId", "appName"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
        },
        appName: {
          type: "string",
          minLength: 1,
          maxLength: 63,
          pattern: "^[a-zA-Z0-9._-]+$",
        },
      },
      additionalProperties: false,
      description: "Input for redis-reload.",
      required: ["appName", "redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-stop",
    operationId: "redis-stop",
    tag: "redis",
    description:
      "Modify Dokploy state via POST /redis.stop. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/redis.stop",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for redis-stop.",
      required: ["redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-saveExternalPort",
    operationId: "redis-saveExternalPort",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.saveExternalPort.",
    method: "POST",
    path: "/redis.saveExternalPort",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId", "externalPort"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
        },
        externalPort: {
          anyOf: [
            {
              type: "number",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for redis-saveExternalPort.",
      required: ["externalPort", "redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-deploy",
    operationId: "redis-deploy",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.deploy.",
    method: "POST",
    path: "/redis.deploy",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for redis-deploy.",
      required: ["redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-changeStatus",
    operationId: "redis-changeStatus",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.changeStatus.",
    method: "POST",
    path: "/redis.changeStatus",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId", "applicationStatus"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
        },
        applicationStatus: {
          type: "string",
          enum: ["idle", "running", "done", "error"],
        },
      },
      additionalProperties: false,
      description: "Input for redis-changeStatus.",
      required: ["applicationStatus", "redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-remove",
    operationId: "redis-remove",
    tag: "redis",
    description:
      "Modify Dokploy state via POST /redis.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/redis.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for redis-remove.",
      required: ["redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-saveEnvironment",
    operationId: "redis-saveEnvironment",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.saveEnvironment.",
    method: "POST",
    path: "/redis.saveEnvironment",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId", "env"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
        },
        env: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for redis-saveEnvironment.",
      required: ["env", "redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-update",
    operationId: "redis-update",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.update.",
    method: "POST",
    path: "/redis.update",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "redisId",
      "name",
      "appName",
      "description",
      "databasePassword",
      "dockerImage",
      "command",
      "args",
      "env",
      "memoryReservation",
      "memoryLimit",
      "cpuReservation",
      "cpuLimit",
      "externalPort",
      "createdAt",
      "applicationStatus",
      "healthCheckSwarm",
      "restartPolicySwarm",
      "placementSwarm",
      "updateConfigSwarm",
      "rollbackConfigSwarm",
      "modeSwarm",
      "labelsSwarm",
      "networkSwarm",
      "stopGracePeriodSwarm",
      "endpointSpecSwarm",
      "ulimitsSwarm",
      "replicas",
      "environmentId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
          minLength: 1,
        },
        appName: {
          type: "string",
          minLength: 1,
          maxLength: 63,
          pattern: "^[a-zA-Z0-9._-]+$",
        },
        description: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        databasePassword: {
          type: "string",
        },
        dockerImage: {
          type: "string",
        },
        command: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        args: {
          anyOf: [
            {
              type: "array",
              items: {
                type: "string",
              },
            },
            {
              type: "null",
            },
          ],
        },
        env: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        memoryReservation: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        memoryLimit: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        cpuReservation: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        cpuLimit: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        externalPort: {
          anyOf: [
            {
              type: "number",
            },
            {
              type: "null",
            },
          ],
        },
        createdAt: {
          type: "string",
        },
        applicationStatus: {
          type: "string",
          enum: ["idle", "running", "done", "error"],
        },
        healthCheckSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Test: {
                      type: "array",
                      items: {
                        type: "string",
                      },
                    },
                    Interval: {
                      type: "number",
                    },
                    Timeout: {
                      type: "number",
                    },
                    StartPeriod: {
                      type: "number",
                    },
                    Retries: {
                      type: "number",
                    },
                  },
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        restartPolicySwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Condition: {
                      type: "string",
                    },
                    Delay: {
                      type: "number",
                    },
                    MaxAttempts: {
                      type: "number",
                    },
                    Window: {
                      type: "number",
                    },
                  },
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        placementSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Constraints: {
                      type: "array",
                      items: {
                        type: "string",
                      },
                    },
                    Preferences: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          Spread: {
                            type: "object",
                            properties: {
                              SpreadDescriptor: {
                                type: "string",
                              },
                            },
                            required: ["SpreadDescriptor"],
                          },
                        },
                        required: ["Spread"],
                        additionalProperties: false,
                      },
                    },
                    MaxReplicas: {
                      type: "number",
                    },
                    Platforms: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          Architecture: {
                            type: "string",
                          },
                          OS: {
                            type: "string",
                          },
                        },
                        required: ["Architecture", "OS"],
                        additionalProperties: false,
                      },
                    },
                  },
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        updateConfigSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Parallelism: {
                      type: "number",
                    },
                    Delay: {
                      type: "number",
                    },
                    FailureAction: {
                      type: "string",
                    },
                    Monitor: {
                      type: "number",
                    },
                    MaxFailureRatio: {
                      type: "number",
                    },
                    Order: {
                      type: "string",
                    },
                  },
                  required: ["Parallelism", "Order"],
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        rollbackConfigSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Parallelism: {
                      type: "number",
                    },
                    Delay: {
                      type: "number",
                    },
                    FailureAction: {
                      type: "string",
                    },
                    Monitor: {
                      type: "number",
                    },
                    MaxFailureRatio: {
                      type: "number",
                    },
                    Order: {
                      type: "string",
                    },
                  },
                  required: ["Parallelism", "Order"],
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        modeSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Replicated: {
                      type: "object",
                      properties: {
                        Replicas: {
                          type: "number",
                        },
                      },
                      additionalProperties: false,
                    },
                    Global: {
                      type: "object",
                      properties: {},
                    },
                    ReplicatedJob: {
                      type: "object",
                      properties: {
                        MaxConcurrent: {
                          type: "number",
                        },
                        TotalCompletions: {
                          type: "number",
                        },
                      },
                      additionalProperties: false,
                    },
                    GlobalJob: {
                      type: "object",
                      properties: {},
                    },
                  },
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        labelsSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  propertyNames: {
                    type: "string",
                  },
                  additionalProperties: {
                    type: "string",
                  },
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        networkSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      Target: {
                        type: "string",
                      },
                      Aliases: {
                        type: "array",
                        items: {
                          type: "string",
                        },
                      },
                      DriverOpts: {
                        type: "object",
                        propertyNames: {
                          type: "string",
                        },
                        additionalProperties: {
                          type: "string",
                        },
                      },
                    },
                    additionalProperties: false,
                  },
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        stopGracePeriodSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "number",
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        endpointSpecSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    Mode: {
                      type: "string",
                    },
                    Ports: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          Protocol: {
                            type: "string",
                          },
                          TargetPort: {
                            type: "number",
                          },
                          PublishedPort: {
                            type: "number",
                          },
                          PublishMode: {
                            type: "string",
                          },
                        },
                        additionalProperties: false,
                      },
                    },
                  },
                  additionalProperties: false,
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        ulimitsSwarm: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      Name: {
                        type: "string",
                        minLength: 1,
                      },
                      Soft: {
                        type: "integer",
                        minimum: -1,
                        maximum: 9007199254740991,
                      },
                      Hard: {
                        type: "integer",
                        minimum: -1,
                        maximum: 9007199254740991,
                      },
                    },
                    required: ["Name", "Soft", "Hard"],
                    additionalProperties: false,
                  },
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        replicas: {
          type: "number",
        },
        environmentId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for redis-update.",
      required: ["redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-changePassword",
    operationId: "redis-changePassword",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.changePassword.",
    method: "POST",
    path: "/redis.changePassword",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId", "password"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
          minLength: 1,
        },
        password: {
          type: "string",
          minLength: 1,
          pattern: "^[a-zA-Z0-9@#%^&*()_+\\-=[\\]{}|;:,.<>?~`]*$",
        },
      },
      additionalProperties: false,
      description: "Input for redis-changePassword.",
      required: ["password", "redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-move",
    operationId: "redis-move",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.move.",
    method: "POST",
    path: "/redis.move",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId", "targetEnvironmentId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
        },
        targetEnvironmentId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for redis-move.",
      required: ["redisId", "targetEnvironmentId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-rebuild",
    operationId: "redis-rebuild",
    tag: "redis",
    description: "Modify Dokploy state via POST /redis.rebuild.",
    method: "POST",
    path: "/redis.rebuild",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redisId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for redis-rebuild.",
      required: ["redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-search",
    operationId: "redis-search",
    tag: "redis",
    description: "Read Dokploy data via GET /redis.search.",
    method: "GET",
    path: "/redis.search",
    pathFields: [],
    queryFields: ["q", "name", "appName", "description", "projectId", "environmentId", "limit", "offset"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        q: {
          type: "string",
        },
        name: {
          type: "string",
        },
        appName: {
          type: "string",
        },
        description: {
          type: "string",
        },
        projectId: {
          type: "string",
        },
        environmentId: {
          type: "string",
        },
        limit: {
          default: 20,
          type: "number",
          minimum: 1,
          maximum: 100,
        },
        offset: {
          default: 0,
          type: "number",
          minimum: 0,
        },
      },
      additionalProperties: false,
      description: "Input for redis-search.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redis-readLogs",
    operationId: "redis-readLogs",
    tag: "redis",
    description: "Read Dokploy data via GET /redis.readLogs.",
    method: "GET",
    path: "/redis.readLogs",
    pathFields: [],
    queryFields: ["redisId", "tail", "since", "search"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redisId: {
          type: "string",
          minLength: 1,
        },
        tail: {
          default: 100,
          type: "integer",
          minimum: 1,
          maximum: 10000,
        },
        since: {
          default: "all",
          type: "string",
          pattern: "^(all|\\d+[smhd])$",
        },
        search: {
          type: "string",
          pattern: "^[a-zA-Z0-9 ._-]{0,500}$",
        },
      },
      additionalProperties: false,
      description: "Input for redis-readLogs.",
      required: ["redisId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
