// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const redirectsOperations: readonly DokployOperationDefinition[] = [
  {
    name: "redirects-create",
    operationId: "redirects-create",
    tag: "redirects",
    description: "Modify Dokploy state via POST /redirects.create.",
    method: "POST",
    path: "/redirects.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["regex", "replacement", "permanent", "applicationId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        regex: {
          type: "string",
          minLength: 1,
        },
        replacement: {
          type: "string",
          minLength: 1,
        },
        permanent: {
          type: "boolean",
        },
        applicationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for redirects-create.",
      required: ["applicationId", "permanent", "regex", "replacement"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redirects-one",
    operationId: "redirects-one",
    tag: "redirects",
    description: "Read Dokploy data via GET /redirects.one.",
    method: "GET",
    path: "/redirects.one",
    pathFields: [],
    queryFields: ["redirectId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redirectId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for redirects-one.",
      required: ["redirectId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redirects-delete",
    operationId: "redirects-delete",
    tag: "redirects",
    description:
      "Modify Dokploy state via POST /redirects.delete. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/redirects.delete",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redirectId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redirectId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for redirects-delete.",
      required: ["redirectId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "redirects-update",
    operationId: "redirects-update",
    tag: "redirects",
    description: "Modify Dokploy state via POST /redirects.update.",
    method: "POST",
    path: "/redirects.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["redirectId", "regex", "replacement", "permanent"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        redirectId: {
          type: "string",
          minLength: 1,
        },
        regex: {
          type: "string",
          minLength: 1,
        },
        replacement: {
          type: "string",
          minLength: 1,
        },
        permanent: {
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for redirects-update.",
      required: ["permanent", "redirectId", "regex", "replacement"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
