// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const registryOperations: readonly DokployOperationDefinition[] = [
  {
    name: "registry-create",
    operationId: "registry-create",
    tag: "registry",
    description: "Modify Dokploy state via POST /registry.create.",
    method: "POST",
    path: "/registry.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["registryName", "username", "password", "registryUrl", "registryType", "imagePrefix", "serverId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        registryName: {
          type: "string",
          minLength: 1,
        },
        username: {
          type: "string",
          minLength: 1,
        },
        password: {
          type: "string",
          minLength: 1,
        },
        registryUrl: {
          type: "string",
        },
        registryType: {
          type: "string",
          enum: ["cloud"],
        },
        imagePrefix: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for registry-create.",
      required: ["imagePrefix", "password", "registryName", "registryType", "registryUrl", "username"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "registry-remove",
    operationId: "registry-remove",
    tag: "registry",
    description:
      "Modify Dokploy state via POST /registry.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/registry.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["registryId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        registryId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for registry-remove.",
      required: ["registryId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "registry-update",
    operationId: "registry-update",
    tag: "registry",
    description: "Modify Dokploy state via POST /registry.update.",
    method: "POST",
    path: "/registry.update",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "registryId",
      "registryName",
      "imagePrefix",
      "username",
      "password",
      "registryUrl",
      "createdAt",
      "registryType",
      "organizationId",
      "serverId",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        registryId: {
          type: "string",
          minLength: 1,
        },
        registryName: {
          type: "string",
          minLength: 1,
        },
        imagePrefix: {
          anyOf: [
            {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            {
              type: "null",
            },
          ],
        },
        username: {
          type: "string",
          minLength: 1,
        },
        password: {
          type: "string",
          minLength: 1,
        },
        registryUrl: {
          type: "string",
        },
        createdAt: {
          type: "string",
        },
        registryType: {
          type: "string",
          enum: ["cloud"],
        },
        organizationId: {
          type: "string",
          minLength: 1,
        },
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for registry-update.",
      required: ["registryId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "registry-all",
    operationId: "registry-all",
    tag: "registry",
    description: "Read Dokploy data via GET /registry.all.",
    method: "GET",
    path: "/registry.all",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for registry-all.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "registry-one",
    operationId: "registry-one",
    tag: "registry",
    description: "Read Dokploy data via GET /registry.one.",
    method: "GET",
    path: "/registry.one",
    pathFields: [],
    queryFields: ["registryId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        registryId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for registry-one.",
      required: ["registryId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "registry-testRegistry",
    operationId: "registry-testRegistry",
    tag: "registry",
    description: "Modify Dokploy state via POST /registry.testRegistry.",
    method: "POST",
    path: "/registry.testRegistry",
    pathFields: [],
    queryFields: [],
    bodyFields: ["registryName", "username", "password", "registryUrl", "registryType", "imagePrefix", "serverId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        registryName: {
          type: "string",
        },
        username: {
          type: "string",
          minLength: 1,
        },
        password: {
          type: "string",
          minLength: 1,
        },
        registryUrl: {
          type: "string",
        },
        registryType: {
          type: "string",
          enum: ["cloud"],
        },
        imagePrefix: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for registry-testRegistry.",
      required: ["password", "registryType", "registryUrl", "username"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "registry-testRegistryById",
    operationId: "registry-testRegistryById",
    tag: "registry",
    description: "Modify Dokploy state via POST /registry.testRegistryById.",
    method: "POST",
    path: "/registry.testRegistryById",
    pathFields: [],
    queryFields: [],
    bodyFields: ["registryId", "serverId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        registryId: {
          type: "string",
          minLength: 1,
        },
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for registry-testRegistryById.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
