// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const rollbackOperations: readonly DokployOperationDefinition[] = [
  {
    name: "rollback-delete",
    operationId: "rollback-delete",
    tag: "rollback",
    description:
      "Modify Dokploy state via POST /rollback.delete. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/rollback.delete",
    pathFields: [],
    queryFields: [],
    bodyFields: ["rollbackId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        rollbackId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for rollback-delete.",
      required: ["rollbackId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "rollback-rollback",
    operationId: "rollback-rollback",
    tag: "rollback",
    description:
      "Modify Dokploy state via POST /rollback.rollback. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/rollback.rollback",
    pathFields: [],
    queryFields: [],
    bodyFields: ["rollbackId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        rollbackId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for rollback-rollback.",
      required: ["rollbackId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
