// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const securityOperations: readonly DokployOperationDefinition[] = [
  {
    name: "security-create",
    operationId: "security-create",
    tag: "security",
    description: "Modify Dokploy state via POST /security.create.",
    method: "POST",
    path: "/security.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["applicationId", "username", "password"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        applicationId: {
          type: "string",
        },
        username: {
          type: "string",
          minLength: 1,
        },
        password: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for security-create.",
      required: ["applicationId", "password", "username"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "security-one",
    operationId: "security-one",
    tag: "security",
    description: "Read Dokploy data via GET /security.one.",
    method: "GET",
    path: "/security.one",
    pathFields: [],
    queryFields: ["securityId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        securityId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for security-one.",
      required: ["securityId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "security-delete",
    operationId: "security-delete",
    tag: "security",
    description:
      "Modify Dokploy state via POST /security.delete. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/security.delete",
    pathFields: [],
    queryFields: [],
    bodyFields: ["securityId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        securityId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for security-delete.",
      required: ["securityId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "security-update",
    operationId: "security-update",
    tag: "security",
    description: "Modify Dokploy state via POST /security.update.",
    method: "POST",
    path: "/security.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["securityId", "username", "password"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        securityId: {
          type: "string",
          minLength: 1,
        },
        username: {
          type: "string",
          minLength: 1,
        },
        password: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for security-update.",
      required: ["password", "securityId", "username"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
