// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const sshKeyOperations: readonly DokployOperationDefinition[] = [
  {
    name: "sshKey-create",
    operationId: "sshKey-create",
    tag: "sshKey",
    description: "Modify Dokploy state via POST /sshKey.create.",
    method: "POST",
    path: "/sshKey.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["name", "description", "privateKey", "publicKey", "organizationId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        description: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        privateKey: {
          type: "string",
        },
        publicKey: {
          type: "string",
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for sshKey-create.",
      required: ["name", "organizationId", "privateKey", "publicKey"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sshKey-remove",
    operationId: "sshKey-remove",
    tag: "sshKey",
    description:
      "Modify Dokploy state via POST /sshKey.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/sshKey.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["sshKeyId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        sshKeyId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for sshKey-remove.",
      required: ["sshKeyId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sshKey-one",
    operationId: "sshKey-one",
    tag: "sshKey",
    description: "Read Dokploy data via GET /sshKey.one.",
    method: "GET",
    path: "/sshKey.one",
    pathFields: [],
    queryFields: ["sshKeyId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        sshKeyId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for sshKey-one.",
      required: ["sshKeyId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sshKey-all",
    operationId: "sshKey-all",
    tag: "sshKey",
    description: "Read Dokploy data via GET /sshKey.all.",
    method: "GET",
    path: "/sshKey.all",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for sshKey-all.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sshKey-allForApps",
    operationId: "sshKey-allForApps",
    tag: "sshKey",
    description: "Read Dokploy data via GET /sshKey.allForApps.",
    method: "GET",
    path: "/sshKey.allForApps",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for sshKey-allForApps.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sshKey-generate",
    operationId: "sshKey-generate",
    tag: "sshKey",
    description: "Modify Dokploy state via POST /sshKey.generate.",
    method: "POST",
    path: "/sshKey.generate",
    pathFields: [],
    queryFields: [],
    bodyFields: ["type"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        type: {
          type: "string",
          enum: ["rsa", "ed25519"],
        },
      },
      additionalProperties: false,
      description: "Input for sshKey-generate.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sshKey-update",
    operationId: "sshKey-update",
    tag: "sshKey",
    description: "Modify Dokploy state via POST /sshKey.update.",
    method: "POST",
    path: "/sshKey.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["name", "description", "lastUsedAt", "sshKeyId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        description: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        lastUsedAt: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        sshKeyId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for sshKey-update.",
      required: ["sshKeyId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
