// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const ssoOperations: readonly DokployOperationDefinition[] = [
  {
    name: "sso-showSignInWithSSO",
    operationId: "sso-showSignInWithSSO",
    tag: "sso",
    description: "Read Dokploy data via GET /sso.showSignInWithSSO.",
    method: "GET",
    path: "/sso.showSignInWithSSO",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for sso-showSignInWithSSO.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sso-listProviders",
    operationId: "sso-listProviders",
    tag: "sso",
    description: "Read Dokploy data via GET /sso.listProviders.",
    method: "GET",
    path: "/sso.listProviders",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for sso-listProviders.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sso-getTrustedOrigins",
    operationId: "sso-getTrustedOrigins",
    tag: "sso",
    description: "Read Dokploy data via GET /sso.getTrustedOrigins.",
    method: "GET",
    path: "/sso.getTrustedOrigins",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for sso-getTrustedOrigins.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sso-one",
    operationId: "sso-one",
    tag: "sso",
    description: "Read Dokploy data via GET /sso.one.",
    method: "GET",
    path: "/sso.one",
    pathFields: [],
    queryFields: ["providerId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        providerId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for sso-one.",
      required: ["providerId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sso-update",
    operationId: "sso-update",
    tag: "sso",
    description: "Modify Dokploy state via POST /sso.update.",
    method: "POST",
    path: "/sso.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["providerId", "issuer", "domains", "oidcConfig", "samlConfig", "organizationId", "overrideUserInfo"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        providerId: {
          type: "string",
        },
        issuer: {
          type: "string",
        },
        domains: {
          type: "array",
          items: {
            type: "string",
          },
        },
        oidcConfig: {
          type: "object",
          properties: {
            clientId: {
              type: "string",
            },
            clientSecret: {
              type: "string",
            },
            authorizationEndpoint: {
              type: "string",
            },
            tokenEndpoint: {
              type: "string",
            },
            userInfoEndpoint: {
              type: "string",
            },
            tokenEndpointAuthentication: {
              type: "string",
              enum: ["client_secret_post", "client_secret_basic"],
            },
            jwksEndpoint: {
              type: "string",
            },
            discoveryEndpoint: {
              type: "string",
            },
            skipDiscovery: {
              type: "boolean",
            },
            scopes: {
              type: "array",
              items: {
                type: "string",
              },
            },
            pkce: {
              default: true,
              type: "boolean",
            },
            mapping: {
              type: "object",
              properties: {
                id: {
                  type: "string",
                },
                email: {
                  type: "string",
                },
                emailVerified: {
                  type: "string",
                },
                name: {
                  type: "string",
                },
                image: {
                  type: "string",
                },
                extraFields: {
                  type: "object",
                  propertyNames: {
                    type: "string",
                  },
                  additionalProperties: {},
                },
              },
              required: ["id", "email", "name"],
            },
          },
          required: ["clientId", "clientSecret"],
        },
        samlConfig: {
          type: "object",
          properties: {
            entryPoint: {
              type: "string",
            },
            cert: {
              type: "string",
            },
            callbackUrl: {
              type: "string",
            },
            audience: {
              type: "string",
            },
            idpMetadata: {
              type: "object",
              properties: {
                metadata: {
                  type: "string",
                },
                entityID: {
                  type: "string",
                },
                cert: {
                  type: "string",
                },
                privateKey: {
                  type: "string",
                },
                privateKeyPass: {
                  type: "string",
                },
                isAssertionEncrypted: {
                  type: "boolean",
                },
                encPrivateKey: {
                  type: "string",
                },
                encPrivateKeyPass: {
                  type: "string",
                },
                singleSignOnService: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      Binding: {
                        type: "string",
                      },
                      Location: {
                        type: "string",
                      },
                    },
                    required: ["Binding", "Location"],
                  },
                },
              },
            },
            spMetadata: {
              type: "object",
              properties: {
                metadata: {
                  type: "string",
                },
                entityID: {
                  type: "string",
                },
                binding: {
                  type: "string",
                },
                privateKey: {
                  type: "string",
                },
                privateKeyPass: {
                  type: "string",
                },
                isAssertionEncrypted: {
                  type: "boolean",
                },
                encPrivateKey: {
                  type: "string",
                },
                encPrivateKeyPass: {
                  type: "string",
                },
              },
            },
            wantAssertionsSigned: {
              type: "boolean",
            },
            authnRequestsSigned: {
              type: "boolean",
            },
            signatureAlgorithm: {
              type: "string",
            },
            digestAlgorithm: {
              type: "string",
            },
            identifierFormat: {
              type: "string",
            },
            privateKey: {
              type: "string",
            },
            decryptionPvk: {
              type: "string",
            },
            additionalParams: {
              type: "object",
              propertyNames: {
                type: "string",
              },
              additionalProperties: {},
            },
            mapping: {
              type: "object",
              properties: {
                id: {
                  type: "string",
                },
                email: {
                  type: "string",
                },
                emailVerified: {
                  type: "string",
                },
                name: {
                  type: "string",
                },
                firstName: {
                  type: "string",
                },
                lastName: {
                  type: "string",
                },
                extraFields: {
                  type: "object",
                  propertyNames: {
                    type: "string",
                  },
                  additionalProperties: {},
                },
              },
              required: ["id", "email", "name"],
            },
          },
          required: ["entryPoint", "cert", "callbackUrl", "spMetadata"],
        },
        organizationId: {
          type: "string",
        },
        overrideUserInfo: {
          default: false,
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for sso-update.",
      required: ["domains", "issuer", "providerId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sso-deleteProvider",
    operationId: "sso-deleteProvider",
    tag: "sso",
    description:
      "Modify Dokploy state via POST /sso.deleteProvider. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/sso.deleteProvider",
    pathFields: [],
    queryFields: [],
    bodyFields: ["providerId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        providerId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for sso-deleteProvider.",
      required: ["providerId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sso-register",
    operationId: "sso-register",
    tag: "sso",
    description: "Modify Dokploy state via POST /sso.register.",
    method: "POST",
    path: "/sso.register",
    pathFields: [],
    queryFields: [],
    bodyFields: ["providerId", "issuer", "domains", "oidcConfig", "samlConfig", "organizationId", "overrideUserInfo"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        providerId: {
          type: "string",
        },
        issuer: {
          type: "string",
        },
        domains: {
          type: "array",
          items: {
            type: "string",
          },
        },
        oidcConfig: {
          type: "object",
          properties: {
            clientId: {
              type: "string",
            },
            clientSecret: {
              type: "string",
            },
            authorizationEndpoint: {
              type: "string",
            },
            tokenEndpoint: {
              type: "string",
            },
            userInfoEndpoint: {
              type: "string",
            },
            tokenEndpointAuthentication: {
              type: "string",
              enum: ["client_secret_post", "client_secret_basic"],
            },
            jwksEndpoint: {
              type: "string",
            },
            discoveryEndpoint: {
              type: "string",
            },
            skipDiscovery: {
              type: "boolean",
            },
            scopes: {
              type: "array",
              items: {
                type: "string",
              },
            },
            pkce: {
              default: true,
              type: "boolean",
            },
            mapping: {
              type: "object",
              properties: {
                id: {
                  type: "string",
                },
                email: {
                  type: "string",
                },
                emailVerified: {
                  type: "string",
                },
                name: {
                  type: "string",
                },
                image: {
                  type: "string",
                },
                extraFields: {
                  type: "object",
                  propertyNames: {
                    type: "string",
                  },
                  additionalProperties: {},
                },
              },
              required: ["id", "email", "name"],
            },
          },
          required: ["clientId", "clientSecret"],
        },
        samlConfig: {
          type: "object",
          properties: {
            entryPoint: {
              type: "string",
            },
            cert: {
              type: "string",
            },
            callbackUrl: {
              type: "string",
            },
            audience: {
              type: "string",
            },
            idpMetadata: {
              type: "object",
              properties: {
                metadata: {
                  type: "string",
                },
                entityID: {
                  type: "string",
                },
                cert: {
                  type: "string",
                },
                privateKey: {
                  type: "string",
                },
                privateKeyPass: {
                  type: "string",
                },
                isAssertionEncrypted: {
                  type: "boolean",
                },
                encPrivateKey: {
                  type: "string",
                },
                encPrivateKeyPass: {
                  type: "string",
                },
                singleSignOnService: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      Binding: {
                        type: "string",
                      },
                      Location: {
                        type: "string",
                      },
                    },
                    required: ["Binding", "Location"],
                  },
                },
              },
            },
            spMetadata: {
              type: "object",
              properties: {
                metadata: {
                  type: "string",
                },
                entityID: {
                  type: "string",
                },
                binding: {
                  type: "string",
                },
                privateKey: {
                  type: "string",
                },
                privateKeyPass: {
                  type: "string",
                },
                isAssertionEncrypted: {
                  type: "boolean",
                },
                encPrivateKey: {
                  type: "string",
                },
                encPrivateKeyPass: {
                  type: "string",
                },
              },
            },
            wantAssertionsSigned: {
              type: "boolean",
            },
            authnRequestsSigned: {
              type: "boolean",
            },
            signatureAlgorithm: {
              type: "string",
            },
            digestAlgorithm: {
              type: "string",
            },
            identifierFormat: {
              type: "string",
            },
            privateKey: {
              type: "string",
            },
            decryptionPvk: {
              type: "string",
            },
            additionalParams: {
              type: "object",
              propertyNames: {
                type: "string",
              },
              additionalProperties: {},
            },
            mapping: {
              type: "object",
              properties: {
                id: {
                  type: "string",
                },
                email: {
                  type: "string",
                },
                emailVerified: {
                  type: "string",
                },
                name: {
                  type: "string",
                },
                firstName: {
                  type: "string",
                },
                lastName: {
                  type: "string",
                },
                extraFields: {
                  type: "object",
                  propertyNames: {
                    type: "string",
                  },
                  additionalProperties: {},
                },
              },
              required: ["id", "email", "name"],
            },
          },
          required: ["entryPoint", "cert", "callbackUrl", "spMetadata"],
        },
        organizationId: {
          type: "string",
        },
        overrideUserInfo: {
          default: false,
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for sso-register.",
      required: ["domains", "issuer", "providerId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sso-addTrustedOrigin",
    operationId: "sso-addTrustedOrigin",
    tag: "sso",
    description: "Modify Dokploy state via POST /sso.addTrustedOrigin.",
    method: "POST",
    path: "/sso.addTrustedOrigin",
    pathFields: [],
    queryFields: [],
    bodyFields: ["origin"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        origin: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for sso-addTrustedOrigin.",
      required: ["origin"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sso-removeTrustedOrigin",
    operationId: "sso-removeTrustedOrigin",
    tag: "sso",
    description:
      "Modify Dokploy state via POST /sso.removeTrustedOrigin. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/sso.removeTrustedOrigin",
    pathFields: [],
    queryFields: [],
    bodyFields: ["origin"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        origin: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for sso-removeTrustedOrigin.",
      required: ["origin"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "sso-updateTrustedOrigin",
    operationId: "sso-updateTrustedOrigin",
    tag: "sso",
    description: "Modify Dokploy state via POST /sso.updateTrustedOrigin.",
    method: "POST",
    path: "/sso.updateTrustedOrigin",
    pathFields: [],
    queryFields: [],
    bodyFields: ["oldOrigin", "newOrigin"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        oldOrigin: {
          type: "string",
          minLength: 1,
        },
        newOrigin: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for sso-updateTrustedOrigin.",
      required: ["newOrigin", "oldOrigin"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
