// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const swarmOperations: readonly DokployOperationDefinition[] = [
  {
    name: "swarm-getNodes",
    operationId: "swarm-getNodes",
    tag: "swarm",
    description: "Read Dokploy data via GET /swarm.getNodes.",
    method: "GET",
    path: "/swarm.getNodes",
    pathFields: [],
    queryFields: ["serverId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for swarm-getNodes.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "swarm-getNodeInfo",
    operationId: "swarm-getNodeInfo",
    tag: "swarm",
    description: "Read Dokploy data via GET /swarm.getNodeInfo.",
    method: "GET",
    path: "/swarm.getNodeInfo",
    pathFields: [],
    queryFields: ["nodeId", "serverId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        nodeId: {
          type: "string",
        },
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for swarm-getNodeInfo.",
      required: ["nodeId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "swarm-getNodeApps",
    operationId: "swarm-getNodeApps",
    tag: "swarm",
    description: "Read Dokploy data via GET /swarm.getNodeApps.",
    method: "GET",
    path: "/swarm.getNodeApps",
    pathFields: [],
    queryFields: ["serverId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for swarm-getNodeApps.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "swarm-getContainerStats",
    operationId: "swarm-getContainerStats",
    tag: "swarm",
    description: "Read Dokploy data via GET /swarm.getContainerStats.",
    method: "GET",
    path: "/swarm.getContainerStats",
    pathFields: [],
    queryFields: ["serverId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        serverId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for swarm-getContainerStats.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
