// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const tagOperations: readonly DokployOperationDefinition[] = [
  {
    name: "tag-create",
    operationId: "tag-create",
    tag: "tag",
    description: "Modify Dokploy state via POST /tag.create.",
    method: "POST",
    path: "/tag.create",
    pathFields: [],
    queryFields: [],
    bodyFields: ["name", "color"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        color: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
      },
      additionalProperties: false,
      description: "Input for tag-create.",
      required: ["name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "tag-all",
    operationId: "tag-all",
    tag: "tag",
    description: "Read Dokploy data via GET /tag.all.",
    method: "GET",
    path: "/tag.all",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for tag-all.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "tag-one",
    operationId: "tag-one",
    tag: "tag",
    description: "Read Dokploy data via GET /tag.one.",
    method: "GET",
    path: "/tag.one",
    pathFields: [],
    queryFields: ["tagId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        tagId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for tag-one.",
      required: ["tagId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "tag-update",
    operationId: "tag-update",
    tag: "tag",
    description: "Modify Dokploy state via POST /tag.update.",
    method: "POST",
    path: "/tag.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["tagId", "name", "color", "createdAt", "organizationId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        tagId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
          minLength: 1,
        },
        color: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        createdAt: {
          type: "string",
        },
        organizationId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for tag-update.",
      required: ["tagId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "tag-remove",
    operationId: "tag-remove",
    tag: "tag",
    description:
      "Modify Dokploy state via POST /tag.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/tag.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["tagId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        tagId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for tag-remove.",
      required: ["tagId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "tag-assignToProject",
    operationId: "tag-assignToProject",
    tag: "tag",
    description: "Modify Dokploy state via POST /tag.assignToProject.",
    method: "POST",
    path: "/tag.assignToProject",
    pathFields: [],
    queryFields: [],
    bodyFields: ["projectId", "tagId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        projectId: {
          type: "string",
          minLength: 1,
        },
        tagId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for tag-assignToProject.",
      required: ["projectId", "tagId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "tag-removeFromProject",
    operationId: "tag-removeFromProject",
    tag: "tag",
    description:
      "Modify Dokploy state via POST /tag.removeFromProject. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/tag.removeFromProject",
    pathFields: [],
    queryFields: [],
    bodyFields: ["projectId", "tagId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        projectId: {
          type: "string",
          minLength: 1,
        },
        tagId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for tag-removeFromProject.",
      required: ["projectId", "tagId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "tag-bulkAssign",
    operationId: "tag-bulkAssign",
    tag: "tag",
    description: "Modify Dokploy state via POST /tag.bulkAssign.",
    method: "POST",
    path: "/tag.bulkAssign",
    pathFields: [],
    queryFields: [],
    bodyFields: ["projectId", "tagIds"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        projectId: {
          type: "string",
          minLength: 1,
        },
        tagIds: {
          type: "array",
          items: {
            type: "string",
            minLength: 1,
          },
        },
      },
      additionalProperties: false,
      description: "Input for tag-bulkAssign.",
      required: ["projectId", "tagIds"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
