// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const userOperations: readonly DokployOperationDefinition[] = [
  {
    name: "user-all",
    operationId: "user-all",
    tag: "user",
    description: "Read Dokploy data via GET /user.all.",
    method: "GET",
    path: "/user.all",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-all.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-one",
    operationId: "user-one",
    tag: "user",
    description: "Read Dokploy data via GET /user.one.",
    method: "GET",
    path: "/user.one",
    pathFields: [],
    queryFields: ["userId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        userId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for user-one.",
      required: ["userId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-session",
    operationId: "user-session",
    tag: "user",
    description: "Read Dokploy data via GET /user.session.",
    method: "GET",
    path: "/user.session",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-session.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-get",
    operationId: "user-get",
    tag: "user",
    description: "Read Dokploy data via GET /user.get.",
    method: "GET",
    path: "/user.get",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-get.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-getPermissions",
    operationId: "user-getPermissions",
    tag: "user",
    description: "Read Dokploy data via GET /user.getPermissions.",
    method: "GET",
    path: "/user.getPermissions",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-getPermissions.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-haveRootAccess",
    operationId: "user-haveRootAccess",
    tag: "user",
    description: "Read Dokploy data via GET /user.haveRootAccess.",
    method: "GET",
    path: "/user.haveRootAccess",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-haveRootAccess.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-getBackups",
    operationId: "user-getBackups",
    tag: "user",
    description: "Read Dokploy data via GET /user.getBackups.",
    method: "GET",
    path: "/user.getBackups",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-getBackups.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-getServerMetrics",
    operationId: "user-getServerMetrics",
    tag: "user",
    description: "Read Dokploy data via GET /user.getServerMetrics.",
    method: "GET",
    path: "/user.getServerMetrics",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-getServerMetrics.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-update",
    operationId: "user-update",
    tag: "user",
    description: "Modify Dokploy state via POST /user.update.",
    method: "POST",
    path: "/user.update",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "id",
      "firstName",
      "lastName",
      "isRegistered",
      "expirationDate",
      "createdAt2",
      "createdAt",
      "twoFactorEnabled",
      "email",
      "emailVerified",
      "image",
      "banned",
      "banReason",
      "banExpires",
      "updatedAt",
      "enablePaidFeatures",
      "allowImpersonation",
      "enableEnterpriseFeatures",
      "licenseKey",
      "stripeCustomerId",
      "stripeSubscriptionId",
      "serversQuantity",
      "sendInvoiceNotifications",
      "password",
      "currentPassword",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
          minLength: 1,
        },
        firstName: {
          type: "string",
        },
        lastName: {
          type: "string",
        },
        isRegistered: {
          type: "boolean",
        },
        expirationDate: {
          type: "string",
        },
        createdAt2: {
          type: "string",
        },
        createdAt: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        twoFactorEnabled: {
          anyOf: [
            {
              type: "boolean",
            },
            {
              type: "null",
            },
          ],
        },
        email: {
          type: "string",
          minLength: 1,
          format: "email",
          pattern:
            "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
        },
        emailVerified: {
          type: "boolean",
        },
        image: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        banned: {
          anyOf: [
            {
              type: "boolean",
            },
            {
              type: "null",
            },
          ],
        },
        banReason: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        banExpires: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        updatedAt: {
          type: "string",
        },
        enablePaidFeatures: {
          type: "boolean",
        },
        allowImpersonation: {
          type: "boolean",
        },
        enableEnterpriseFeatures: {
          type: "boolean",
        },
        licenseKey: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        stripeCustomerId: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        stripeSubscriptionId: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        serversQuantity: {
          type: "number",
        },
        sendInvoiceNotifications: {
          type: "boolean",
        },
        password: {
          type: "string",
        },
        currentPassword: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for user-update.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-getUserByToken",
    operationId: "user-getUserByToken",
    tag: "user",
    description: "Read Dokploy data via GET /user.getUserByToken.",
    method: "GET",
    path: "/user.getUserByToken",
    pathFields: [],
    queryFields: ["token"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        token: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for user-getUserByToken.",
      required: ["token"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-getMetricsToken",
    operationId: "user-getMetricsToken",
    tag: "user",
    description: "Read Dokploy data via GET /user.getMetricsToken.",
    method: "GET",
    path: "/user.getMetricsToken",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-getMetricsToken.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-remove",
    operationId: "user-remove",
    tag: "user",
    description:
      "Modify Dokploy state via POST /user.remove. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/user.remove",
    pathFields: [],
    queryFields: [],
    bodyFields: ["userId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        userId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for user-remove.",
      required: ["userId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-assignPermissions",
    operationId: "user-assignPermissions",
    tag: "user",
    description: "Modify Dokploy state via POST /user.assignPermissions.",
    method: "POST",
    path: "/user.assignPermissions",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "id",
      "accessedProjects",
      "accessedEnvironments",
      "accessedServices",
      "accessedGitProviders",
      "accessedServers",
      "canCreateProjects",
      "canCreateServices",
      "canDeleteProjects",
      "canDeleteServices",
      "canAccessToDocker",
      "canAccessToTraefikFiles",
      "canAccessToAPI",
      "canAccessToSSHKeys",
      "canAccessToGitProviders",
      "canDeleteEnvironments",
      "canCreateEnvironments",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
          minLength: 1,
        },
        accessedProjects: {
          type: "array",
          items: {
            type: "string",
          },
        },
        accessedEnvironments: {
          type: "array",
          items: {
            type: "string",
          },
        },
        accessedServices: {
          type: "array",
          items: {
            type: "string",
          },
        },
        accessedGitProviders: {
          type: "array",
          items: {
            type: "string",
          },
        },
        accessedServers: {
          type: "array",
          items: {
            type: "string",
          },
        },
        canCreateProjects: {
          type: "boolean",
        },
        canCreateServices: {
          type: "boolean",
        },
        canDeleteProjects: {
          type: "boolean",
        },
        canDeleteServices: {
          type: "boolean",
        },
        canAccessToDocker: {
          type: "boolean",
        },
        canAccessToTraefikFiles: {
          type: "boolean",
        },
        canAccessToAPI: {
          type: "boolean",
        },
        canAccessToSSHKeys: {
          type: "boolean",
        },
        canAccessToGitProviders: {
          type: "boolean",
        },
        canDeleteEnvironments: {
          type: "boolean",
        },
        canCreateEnvironments: {
          type: "boolean",
        },
      },
      additionalProperties: false,
      description: "Input for user-assignPermissions.",
      required: [
        "accessedEnvironments",
        "accessedGitProviders",
        "accessedProjects",
        "accessedServers",
        "accessedServices",
        "canAccessToAPI",
        "canAccessToDocker",
        "canAccessToGitProviders",
        "canAccessToSSHKeys",
        "canAccessToTraefikFiles",
        "canCreateEnvironments",
        "canCreateProjects",
        "canCreateServices",
        "canDeleteEnvironments",
        "canDeleteProjects",
        "canDeleteServices",
        "id",
      ],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-getInvitations",
    operationId: "user-getInvitations",
    tag: "user",
    description: "Read Dokploy data via GET /user.getInvitations.",
    method: "GET",
    path: "/user.getInvitations",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-getInvitations.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-getContainerMetrics",
    operationId: "user-getContainerMetrics",
    tag: "user",
    description: "Read Dokploy data via GET /user.getContainerMetrics.",
    method: "GET",
    path: "/user.getContainerMetrics",
    pathFields: [],
    queryFields: ["url", "token", "appName", "dataPoints"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        url: {
          type: "string",
        },
        token: {
          type: "string",
        },
        appName: {
          type: "string",
        },
        dataPoints: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for user-getContainerMetrics.",
      required: ["appName", "dataPoints", "token", "url"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-generateToken",
    operationId: "user-generateToken",
    tag: "user",
    description: "Modify Dokploy state via POST /user.generateToken.",
    method: "POST",
    path: "/user.generateToken",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-generateToken.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-deleteApiKey",
    operationId: "user-deleteApiKey",
    tag: "user",
    description:
      "Modify Dokploy state via POST /user.deleteApiKey. Warning: this operation can remove, stop, or otherwise disrupt resources.",
    method: "POST",
    path: "/user.deleteApiKey",
    pathFields: [],
    queryFields: [],
    bodyFields: ["apiKeyId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        apiKeyId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for user-deleteApiKey.",
      required: ["apiKeyId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-createApiKey",
    operationId: "user-createApiKey",
    tag: "user",
    description: "Modify Dokploy state via POST /user.createApiKey.",
    method: "POST",
    path: "/user.createApiKey",
    pathFields: [],
    queryFields: [],
    bodyFields: [
      "name",
      "prefix",
      "expiresIn",
      "metadata",
      "rateLimitEnabled",
      "rateLimitTimeWindow",
      "rateLimitMax",
      "remaining",
      "refillAmount",
      "refillInterval",
    ],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        name: {
          type: "string",
          minLength: 1,
        },
        prefix: {
          type: "string",
        },
        expiresIn: {
          type: "number",
        },
        metadata: {
          type: "object",
          properties: {
            organizationId: {
              type: "string",
            },
          },
          required: ["organizationId"],
        },
        rateLimitEnabled: {
          type: "boolean",
        },
        rateLimitTimeWindow: {
          type: "number",
        },
        rateLimitMax: {
          type: "number",
        },
        remaining: {
          type: "number",
        },
        refillAmount: {
          type: "number",
        },
        refillInterval: {
          type: "number",
        },
      },
      additionalProperties: false,
      description: "Input for user-createApiKey.",
      required: ["metadata", "name"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-checkUserOrganizations",
    operationId: "user-checkUserOrganizations",
    tag: "user",
    description: "Read Dokploy data via GET /user.checkUserOrganizations.",
    method: "GET",
    path: "/user.checkUserOrganizations",
    pathFields: [],
    queryFields: ["userId"],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        userId: {
          type: "string",
        },
      },
      additionalProperties: false,
      description: "Input for user-checkUserOrganizations.",
      required: ["userId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-createUserWithCredentials",
    operationId: "user-createUserWithCredentials",
    tag: "user",
    description: "Modify Dokploy state via POST /user.createUserWithCredentials.",
    method: "POST",
    path: "/user.createUserWithCredentials",
    pathFields: [],
    queryFields: [],
    bodyFields: ["email", "password", "role"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        email: {
          type: "string",
          format: "email",
          pattern:
            "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
        },
        password: {
          type: "string",
          minLength: 8,
        },
        role: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for user-createUserWithCredentials.",
      required: ["email", "password", "role"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-sendInvitation",
    operationId: "user-sendInvitation",
    tag: "user",
    description: "Modify Dokploy state via POST /user.sendInvitation.",
    method: "POST",
    path: "/user.sendInvitation",
    pathFields: [],
    queryFields: [],
    bodyFields: ["invitationId", "notificationId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        invitationId: {
          type: "string",
          minLength: 1,
        },
        notificationId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for user-sendInvitation.",
      required: ["invitationId", "notificationId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-getBookmarkedTemplates",
    operationId: "user-getBookmarkedTemplates",
    tag: "user",
    description: "Read Dokploy data via GET /user.getBookmarkedTemplates.",
    method: "GET",
    path: "/user.getBookmarkedTemplates",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for user-getBookmarkedTemplates.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "user-toggleTemplateBookmark",
    operationId: "user-toggleTemplateBookmark",
    tag: "user",
    description: "Modify Dokploy state via POST /user.toggleTemplateBookmark.",
    method: "POST",
    path: "/user.toggleTemplateBookmark",
    pathFields: [],
    queryFields: [],
    bodyFields: ["templateId"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        templateId: {
          type: "string",
          minLength: 1,
        },
      },
      additionalProperties: false,
      description: "Input for user-toggleTemplateBookmark.",
      required: ["templateId"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
