// Generated by src/providers/dokploy/generate.ts from Dokploy/mcp@db18449eafdfc8dbd438d392b95c46292069c658/src/generated/openapi.json.
// Do not edit by hand; update the source OpenAPI document and regenerate.

import type { DokployOperationDefinition } from "../operations.ts";

export const whitelabelingOperations: readonly DokployOperationDefinition[] = [
  {
    name: "whitelabeling-get",
    operationId: "whitelabeling-get",
    tag: "whitelabeling",
    description: "Read Dokploy data via GET /whitelabeling.get.",
    method: "GET",
    path: "/whitelabeling.get",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for whitelabeling-get.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "whitelabeling-update",
    operationId: "whitelabeling-update",
    tag: "whitelabeling",
    description: "Modify Dokploy state via POST /whitelabeling.update.",
    method: "POST",
    path: "/whitelabeling.update",
    pathFields: [],
    queryFields: [],
    bodyFields: ["whitelabelingConfig"],
    fileFields: [],
    contentType: "application/json",
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {
        whitelabelingConfig: {
          type: "object",
          properties: {
            appName: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            appDescription: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            logoUrl: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            faviconUrl: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            customCss: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            loginLogoUrl: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            supportUrl: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            docsUrl: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            errorPageTitle: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            errorPageDescription: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            metaTitle: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            footerText: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
          },
          required: [
            "appName",
            "appDescription",
            "logoUrl",
            "faviconUrl",
            "customCss",
            "loginLogoUrl",
            "supportUrl",
            "docsUrl",
            "errorPageTitle",
            "errorPageDescription",
            "metaTitle",
            "footerText",
          ],
        },
      },
      additionalProperties: false,
      description: "Input for whitelabeling-update.",
      required: ["whitelabelingConfig"],
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "whitelabeling-reset",
    operationId: "whitelabeling-reset",
    tag: "whitelabeling",
    description: "Modify Dokploy state via POST /whitelabeling.reset.",
    method: "POST",
    path: "/whitelabeling.reset",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for whitelabeling-reset.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
  {
    name: "whitelabeling-getPublic",
    operationId: "whitelabeling-getPublic",
    tag: "whitelabeling",
    description: "Read Dokploy data via GET /whitelabeling.getPublic.",
    method: "GET",
    path: "/whitelabeling.getPublic",
    pathFields: [],
    queryFields: [],
    bodyFields: [],
    fileFields: [],
    contentType: null,
    supportStatus: "supported",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
      description: "Input for whitelabeling-getPublic.",
    },
    outputSchema: {
      description: "Successful response",
    },
  },
];
