import type { ActionDefinition, JsonSchema } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";
import { defineProviderAction } from "../../core/provider-definition.ts";

const service = "hashnode";

const userSummarySchema = s.requiredObject("A Hashnode user summary.", {
  id: s.string("The Hashnode user ID."),
  username: s.string("The Hashnode username."),
  name: s.string("The user's display name."),
});

const currentUserSchema = s.requiredObject("The authenticated Hashnode user's profile.", {
  id: s.string("The authenticated user's Hashnode ID."),
  username: s.string("The authenticated user's Hashnode username."),
  name: s.string("The authenticated user's display name."),
  email: s.string("The authenticated user's email address."),
  profilePicture: s.nullableString("The user's profile picture URL when configured."),
  tagline: s.nullableString("The user's profile tagline when configured."),
  location: s.nullableString("The user's profile location when configured."),
  dateJoined: s.nullableString("The user's join timestamp in ISO 8601 format when available."),
});

const publicationSummarySchema = s.requiredObject("A Hashnode publication summary.", {
  id: s.string("The Hashnode publication ID."),
  title: s.string("The publication title."),
  url: s.nullableString("The publication URL when configured."),
  isTeam: s.boolean("Whether the publication is a team publication."),
});

const pageInfoSchema = s.requiredObject("Hashnode cursor pagination metadata.", {
  hasNextPage: s.boolean("Whether another page exists after this page."),
  endCursor: s.nullableString("The cursor to pass as after for the next page."),
});

const tagSchema = s.requiredObject("A Hashnode tag.", {
  id: s.string("The Hashnode tag ID."),
  name: s.string("The tag name."),
  slug: s.string("The tag slug."),
});

const contentSchema = s.requiredObject("Hashnode post or draft content.", {
  markdown: s.string("The content in Markdown format."),
  html: s.string("The content rendered as HTML by Hashnode."),
});

const postSummaryProperties: Record<string, JsonSchema> = {
  id: s.string("The Hashnode post ID."),
  title: s.string("The post title."),
  subtitle: s.nullableString("The post subtitle when configured."),
  slug: s.string("The post slug."),
  url: s.string("The published post URL."),
  brief: s.string("The post summary generated by Hashnode."),
  publishedAt: s.string("The publication timestamp in ISO 8601 format."),
  updatedAt: s.nullableString("The last update timestamp in ISO 8601 format."),
};

const postSummarySchema = s.requiredObject("A Hashnode post summary.", postSummaryProperties);

const postSchema = s.requiredObject("A published Hashnode post.", {
  ...postSummaryProperties,
  content: contentSchema,
  author: userSummarySchema,
  tags: s.nullable(s.array("The tags attached to the post.", tagSchema)),
  readTimeInMinutes: s.integer("The estimated reading time in minutes."),
  views: s.nullable(s.integer("The post view count when available.")),
});

const postMutationResultSchema = s.requiredObject("A post returned by a Hashnode write mutation.", {
  id: s.string("The Hashnode post ID."),
  title: s.string("The post title."),
  slug: s.string("The post slug."),
  url: s.string("The published post URL."),
  publishedAt: s.string("The publication timestamp in ISO 8601 format."),
  updatedAt: s.nullableString("The last update timestamp in ISO 8601 format."),
});

const draftSchema = s.requiredObject("A Hashnode draft.", {
  id: s.string("The Hashnode draft ID."),
  title: s.nullableString("The draft title when configured."),
  subtitle: s.nullableString("The draft subtitle when configured."),
  slug: s.nullableString("The draft slug when configured."),
  content: s.nullable(contentSchema),
  author: userSummarySchema,
  publication: s.nullable(publicationSummarySchema),
  tags: s.nullable(s.array("The tags attached to the draft.", tagSchema)),
  updatedAt: s.string("The last draft update timestamp in ISO 8601 format."),
  scheduledDate: s.nullableString("The scheduled publication timestamp when configured."),
  isSubmittedForReview: s.nullable(s.boolean("Whether the draft has been submitted for editorial review.")),
});

const tagInputSchema = s.object(
  "A tag to attach to a Hashnode post or draft.",
  {
    slug: s.nonEmptyString("The tag slug used to find or create the tag."),
    name: s.nonEmptyString("The tag display name; Hashnode defaults it to the slug."),
  },
  { optional: ["name"] },
);

const tagsInputSchema = s.array("The tags to attach, up to Hashnode's limit of 15.", tagInputSchema, {
  maxItems: 15,
});

const optionalPostFields = {
  subtitle: s.string("The optional post subtitle."),
  coverImage: s.url("The public URL of the post cover image."),
  slug: s.nonEmptyString("The custom post slug; Hashnode generates one when omitted."),
  tags: tagsInputSchema,
  originalArticleURL: s.url("The canonical URL when this post was originally published elsewhere."),
  metaTitle: s.string("The optional SEO title override."),
  metaDescription: s.string("The optional SEO description override."),
  ogImage: s.url("The public URL of the Open Graph image override."),
  disableComments: s.boolean("Whether comments should be disabled on the post."),
  isDelisted: s.boolean("Whether the post should be excluded from feeds."),
  enableToc: s.boolean("Whether Hashnode should expose a table of contents for the post."),
  seriesId: s.nonEmptyString("The ID of a series in the target publication."),
  publishedAt: s.dateTime("The timestamp to use when backdating the post."),
};

const updatePostFields = {
  title: s.nullable(s.string("The updated post title.")),
  contentMarkdown: s.nullable(s.string("The updated post content in Markdown format.")),
  subtitle: s.nullable(s.string("The updated post subtitle.")),
  coverImage: s.nullable(s.url("The updated public URL of the post cover image.")),
  slug: s.nullable(s.nonEmptyString("The updated post slug.")),
  tags: s.nullable(tagsInputSchema),
  originalArticleURL: s.nullable(s.url("The updated canonical URL when this post was originally published elsewhere.")),
  metaTitle: s.nullable(s.string("The updated SEO title override.")),
  metaDescription: s.nullable(s.string("The updated SEO description override.")),
  ogImage: s.nullable(s.url("The updated public URL of the Open Graph image override.")),
  disableComments: s.nullable(s.boolean("Whether comments should be disabled on the post.")),
  isDelisted: s.nullable(s.boolean("Whether the post should be excluded from feeds.")),
  enableToc: s.nullable(s.boolean("Whether Hashnode should expose a table of contents for the post.")),
  seriesId: s.nullable(s.nonEmptyString("The updated series ID, or null to remove the series.")),
  publishedAt: s.nullable(s.dateTime("The updated backdated publication timestamp.")),
};

const optionalDraftFields = {
  title: s.string("The optional draft title."),
  subtitle: s.string("The optional draft subtitle."),
  contentMarkdown: s.string("The optional draft content in Markdown format."),
  slug: s.nonEmptyString("The optional custom slug for the resulting post."),
  tags: tagsInputSchema,
  seriesId: s.nonEmptyString("The ID of a series in the target publication."),
  disableComments: s.boolean("Whether comments should be disabled on the resulting post."),
  originalArticleURL: s.url("The canonical URL when the resulting post was originally published elsewhere."),
  publishedAt: s.dateTime("The timestamp to use when backdating the resulting post."),
};

const updateDraftFields = {
  title: s.nullable(s.string("The updated draft title.")),
  subtitle: s.nullable(s.string("The updated draft subtitle.")),
  contentMarkdown: s.nullable(s.string("The updated draft content in Markdown format.")),
  slug: s.nullable(s.nonEmptyString("The updated custom slug for the resulting post.")),
  tags: s.nullable(tagsInputSchema),
  seriesId: s.nullable(s.nonEmptyString("The updated series ID, or null to remove the draft from a series.")),
  disableComments: s.nullable(s.boolean("Whether comments should be disabled on the resulting post.")),
  originalArticleURL: s.nullable(s.url("The updated canonical URL for the resulting post.")),
  publishedAt: s.nullable(s.dateTime("The updated backdated timestamp for the resulting post.")),
};

const getCurrentUserAction = defineProviderAction(service, {
  name: "get_current_user",
  description: "Get the profile for the user authenticated by the connected Hashnode PAT.",
  requiredScopes: [],
  inputSchema: s.object("Input for fetching the authenticated Hashnode user.", {}),
  outputSchema: s.requiredObject("The authenticated Hashnode user.", {
    user: currentUserSchema,
  }),
});

const listMyPublicationsAction = defineProviderAction(service, {
  name: "list_my_publications",
  description: "List publications available to the authenticated Hashnode user.",
  requiredScopes: [],
  inputSchema: s.object(
    "Input for listing the authenticated user's Hashnode publications.",
    {
      first: s.integer("The number of publications to return, from 1 through 100.", {
        minimum: 1,
        maximum: 100,
        default: 20,
      }),
      after: s.nonEmptyString("The cursor returned by the previous page."),
    },
    { optional: ["first", "after"] },
  ),
  outputSchema: s.requiredObject("A page of the user's Hashnode publications.", {
    publications: s.array("The publications on this page.", publicationSummarySchema),
    pageInfo: pageInfoSchema,
  }),
});

const getPostAction = defineProviderAction(service, {
  name: "get_post",
  description: "Get one published Hashnode post by ID, including Markdown and rendered HTML.",
  requiredScopes: [],
  inputSchema: s.requiredObject("Input for fetching a published Hashnode post.", {
    id: s.nonEmptyString("The Hashnode post ID."),
  }),
  outputSchema: s.requiredObject("The Hashnode post when it exists.", {
    post: s.nullable(postSchema),
  }),
});

const listPublicationPostsInputSchema = s.object(
  "Input for listing posts from one Hashnode publication.",
  {
    publicationId: s.nonEmptyString("The publication ID; provide this or host, but not both."),
    host: s.nonEmptyString("The publication host; provide this or publicationId, but not both."),
    first: s.integer("The number of posts to return, from 1 through 100.", {
      minimum: 1,
      maximum: 100,
      default: 20,
    }),
    after: s.nonEmptyString("The cursor returned by the previous page."),
  },
  { optional: ["publicationId", "host", "first", "after"] },
);
listPublicationPostsInputSchema.oneOf = [{ required: ["publicationId"] }, { required: ["host"] }];

const listPublicationPostsAction = defineProviderAction(service, {
  name: "list_publication_posts",
  description:
    "List posts from a Hashnode publication with cursor pagination; the publication must have an active Pro plan.",
  requiredScopes: [],
  inputSchema: listPublicationPostsInputSchema,
  outputSchema: s.requiredObject("A page of posts from the requested Hashnode publication.", {
    publication: publicationSummarySchema,
    posts: s.array("The posts on this page.", postSummarySchema),
    pageInfo: pageInfoSchema,
  }),
});

const publishPostAction = defineProviderAction(service, {
  name: "publish_post",
  description: "Publish a Markdown post to a Hashnode publication with an active Pro plan.",
  requiredScopes: [],
  inputSchema: s.object(
    "Input for publishing a Hashnode post.",
    {
      publicationId: s.nonEmptyString("The ID of the target Hashnode publication."),
      title: s.nonEmptyString("The post title."),
      contentMarkdown: s.string("The post content in Markdown format.", { minLength: 1 }),
      ...optionalPostFields,
    },
    { optional: Object.keys(optionalPostFields) },
  ),
  outputSchema: s.requiredObject("The post published by Hashnode.", {
    post: postMutationResultSchema,
  }),
});

const updatePostAction = defineProviderAction(service, {
  name: "update_post",
  description: "Update fields on an existing Hashnode post in a Pro publication.",
  requiredScopes: [],
  inputSchema: s.object(
    "Input for updating a Hashnode post.",
    {
      id: s.nonEmptyString("The ID of the Hashnode post to update."),
      ...updatePostFields,
    },
    {
      optional: Object.keys(updatePostFields),
    },
  ),
  outputSchema: s.requiredObject("The post updated by Hashnode.", {
    post: postMutationResultSchema,
  }),
});

const getDraftAction = defineProviderAction(service, {
  name: "get_draft",
  description: "Get one accessible Hashnode draft by ID from a Pro publication.",
  requiredScopes: [],
  inputSchema: s.requiredObject("Input for fetching a Hashnode draft.", {
    id: s.nonEmptyString("The Hashnode draft ID."),
  }),
  outputSchema: s.requiredObject("The Hashnode draft when it exists and is accessible.", {
    draft: s.nullable(draftSchema),
  }),
});

const createDraftAction = defineProviderAction(service, {
  name: "create_draft",
  description: "Create a draft in a Hashnode publication with an active Pro plan.",
  requiredScopes: [],
  inputSchema: s.object(
    "Input for creating a Hashnode draft.",
    {
      publicationId: s.nonEmptyString("The ID of the target Hashnode publication."),
      ...optionalDraftFields,
    },
    { optional: Object.keys(optionalDraftFields) },
  ),
  outputSchema: s.requiredObject("The draft created by Hashnode.", {
    draft: draftSchema,
  }),
});

const updateDraftAction = defineProviderAction(service, {
  name: "update_draft",
  description: "Update fields on an existing Hashnode draft in a Pro publication.",
  requiredScopes: [],
  inputSchema: s.object(
    "Input for updating a Hashnode draft.",
    {
      draftId: s.nonEmptyString("The ID of the Hashnode draft to update."),
      ...updateDraftFields,
    },
    { optional: Object.keys(updateDraftFields) },
  ),
  outputSchema: s.requiredObject("The draft updated by Hashnode.", {
    draft: draftSchema,
  }),
});

const publishDraftAction = defineProviderAction(service, {
  name: "publish_draft",
  description: "Publish an existing Hashnode draft from a Pro publication.",
  requiredScopes: [],
  inputSchema: s.requiredObject("Input for publishing a Hashnode draft.", {
    draftId: s.nonEmptyString("The ID of the Hashnode draft to publish."),
  }),
  outputSchema: s.requiredObject("The post created from the Hashnode draft.", {
    post: postMutationResultSchema,
  }),
});

const deleteDraftAction = defineProviderAction(service, {
  name: "delete_draft",
  description: "Soft-delete an accessible Hashnode draft from a Pro publication.",
  requiredScopes: [],
  inputSchema: s.requiredObject("Input for deleting a Hashnode draft.", {
    draftId: s.nonEmptyString("The ID of the Hashnode draft to delete."),
  }),
  outputSchema: s.requiredObject("The deleted Hashnode draft when returned by the API.", {
    draft: s.nullable(draftSchema),
  }),
});

export const hashnodeActions: ActionDefinition[] = [
  getCurrentUserAction,
  listMyPublicationsAction,
  getPostAction,
  listPublicationPostsAction,
  publishPostAction,
  updatePostAction,
  getDraftAction,
  createDraftAction,
  updateDraftAction,
  publishDraftAction,
  deleteDraftAction,
];
