import type { ActionDefinition, JsonSchema } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";
import { defineProviderAction } from "../../core/provider-definition.ts";

const service = "crypto_apis";

const contextSchema = s.string(
  "A client-provided context value returned by Crypto APIs to correlate responses with requests.",
);
const responseMetadataProperties: Record<string, JsonSchema> = {
  apiVersion: s.nonEmptyString("The Crypto APIs REST API version that handled the request."),
  requestId: s.nonEmptyString("The unique request ID generated by Crypto APIs."),
  context: contextSchema,
};
const assetTypeSchema = s.stringEnum("The supported asset type.", ["fiat", "crypto"]);
const logoSchema = s.requiredObject("Encoded asset logo data returned by Crypto APIs.", {
  encoding: s.nonEmptyString("The encoding of the image data, usually base64."),
  imageData: s.nonEmptyString("The encoded image data."),
  mimeType: s.nonEmptyString("The MIME type of the encoded logo image."),
});
const latestRateSchema = s.object(
  "The latest USD-denominated market rate returned for an asset.",
  {
    amount: s.nonEmptyString("The latest rate amount."),
    calculationTimestamp: s.integer("The UNIX timestamp when Crypto APIs calculated the latest rate."),
    unit: s.nonEmptyString("The unit of the latest asset price."),
  },
  { optional: ["calculationTimestamp"] },
);
const assetProperties: Record<string, JsonSchema> = {
  latestRate: latestRateSchema,
  logo: logoSchema,
  name: s.nonEmptyString("The asset name."),
  originalSymbol: s.nonEmptyString("The asset symbol as introduced by its founders."),
  referenceId: s.nonEmptyString("The unique Crypto APIs reference ID for the asset."),
  slug: s.nonEmptyString("The asset slug in Crypto APIs listings."),
  specificData: s.looseObject("Provider-specific market data for the asset."),
  symbol: s.nonEmptyString("The unique asset symbol in Crypto APIs listings."),
  type: assetTypeSchema,
};
const supportedAssetSchema = s.looseRequiredObject(
  "A supported Crypto APIs market data asset, including its latest price and provider-specific market data.",
  assetProperties,
  { optional: ["slug"] },
);
const assetDetailsSchema = s.looseRequiredObject("Detailed Crypto APIs market data for one asset.", assetProperties, {
  optional: ["latestRate", "logo", "slug", "specificData"],
});
const listSupportedAssetsOutputSchema = s.object(
  "The supported assets returned by Crypto APIs.",
  {
    ...responseMetadataProperties,
    limit: s.integer("The number of items requested per page."),
    offset: s.integer("The starting index of returned items."),
    total: s.integer("The total number of supported assets matching the request."),
    items: s.array("The supported assets on this page.", supportedAssetSchema),
  },
  { optional: ["context"] },
);
const exchangeRateSchema = s.requiredObject("A Crypto APIs exchange rate between two assets.", {
  calculationTimestamp: s.integer("The UNIX timestamp for the market data used to calculate the rate."),
  fromAssetId: s.nonEmptyString("The base asset reference ID."),
  fromAssetSymbol: s.nonEmptyString("The base asset symbol."),
  rate: s.nonEmptyString("The exchange rate calculated from weighted recent exchange trades."),
  toAssetId: s.nonEmptyString("The relation asset reference ID."),
  toAssetSymbol: s.nonEmptyString("The relation asset symbol."),
});
const exchangeRateOutputSchema = s.object(
  "The exchange rate response returned by Crypto APIs.",
  {
    ...responseMetadataProperties,
    item: exchangeRateSchema,
  },
  { optional: ["context"] },
);
const assetDetailsOutputSchema = s.object(
  "The asset details response returned by Crypto APIs.",
  {
    ...responseMetadataProperties,
    item: assetDetailsSchema,
  },
  { optional: ["context"] },
);
const exchangeRateTimestampSchema = s.integer(
  "The optional UNIX timestamp for historical market data used to calculate the exchange rate. Crypto APIs supports up to 30 days back.",
);

export const cryptoApisActions: ActionDefinition[] = [
  defineProviderAction(service, {
    name: "list_supported_assets",
    description: "List fiat and cryptocurrency assets supported by Crypto APIs market data endpoints.",
    inputSchema: s.object(
      "The input for listing supported Crypto APIs assets.",
      {
        context: contextSchema,
        limit: s.integer("The number of assets to return per page.", { minimum: 0, maximum: 50 }),
        offset: s.nonNegativeInteger("The starting index for returned assets."),
        type: assetTypeSchema,
      },
      { optional: ["context", "limit", "offset", "type"] },
    ),
    outputSchema: listSupportedAssetsOutputSchema,
  }),
  defineProviderAction(service, {
    name: "get_exchange_rate_by_symbols",
    description: "Get the exchange rate for one asset symbol versus another asset symbol from Crypto APIs.",
    inputSchema: s.object(
      "The input for retrieving an exchange rate by asset symbols.",
      {
        fromAssetSymbol: s.nonEmptyString("The base asset symbol to get a rate for."),
        toAssetSymbol: s.nonEmptyString("The relation asset symbol in which the base asset rate is displayed."),
        context: contextSchema,
        calculationTimestamp: exchangeRateTimestampSchema,
      },
      { optional: ["context", "calculationTimestamp"] },
    ),
    outputSchema: exchangeRateOutputSchema,
  }),
  defineProviderAction(service, {
    name: "get_exchange_rate_by_asset_ids",
    description: "Get the exchange rate for one Crypto APIs asset reference ID versus another asset reference ID.",
    inputSchema: s.object(
      "The input for retrieving an exchange rate by asset reference IDs.",
      {
        fromAssetId: s.nonEmptyString("The base asset reference ID to get a rate for."),
        toAssetId: s.nonEmptyString("The relation asset reference ID in which the base asset rate is displayed."),
        context: contextSchema,
        calculationTimestamp: exchangeRateTimestampSchema,
      },
      { optional: ["context", "calculationTimestamp"] },
    ),
    outputSchema: exchangeRateOutputSchema,
  }),
  defineProviderAction(service, {
    name: "get_asset_details_by_symbol",
    description: "Get detailed Crypto APIs market data for one asset by its asset symbol.",
    inputSchema: s.object(
      "The input for retrieving asset details by symbol.",
      {
        assetSymbol: s.nonEmptyString("The asset symbol in Crypto APIs listings."),
        context: contextSchema,
      },
      { optional: ["context"] },
    ),
    outputSchema: assetDetailsOutputSchema,
  }),
  defineProviderAction(service, {
    name: "get_asset_details_by_id",
    description: "Get detailed Crypto APIs market data for one asset by its Crypto APIs reference ID.",
    inputSchema: s.object(
      "The input for retrieving asset details by reference ID.",
      {
        assetId: s.nonEmptyString("The unique Crypto APIs reference ID for the asset."),
        context: contextSchema,
      },
      { optional: ["context"] },
    ),
    outputSchema: assetDetailsOutputSchema,
  }),
];
