import type { ActionDefinition } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";
import { defineProviderAction } from "../../core/provider-definition.ts";

const service = "eraser";

const diagramTypeSchema = s.stringEnum("The Eraser diagram type.", [
  "sequence-diagram",
  "entity-relationship-diagram",
  "cloud-architecture-diagram",
  "flowchart-diagram",
  "bpmn-diagram",
]);
const linkAccessSchema = s.stringEnum("The link access setting for the Eraser file.", [
  "no-link-access",
  "anyone-with-link-can-edit",
  "publicly-viewable",
  "publicly-editable",
  "sso-readable",
  "sso-editable",
]);
const fileOptionsSchema = s.object(
  "Options for creating an editable Eraser file from the generated diagram.",
  {
    create: s.boolean("Whether to create an Eraser file immediately."),
    linkAccess: linkAccessSchema,
  },
  { optional: ["create", "linkAccess"] },
);
const diagramSchema = s.looseRequiredObject("An Eraser diagram and its current DSL content.", {
  id: s.string("The unique diagram identifier."),
  diagramUrl: s.string("The URL for viewing the diagram in Eraser.", { format: "uri" }),
  diagramType: diagramTypeSchema,
  code: s.string("The Eraser DSL source for the diagram."),
  updatedAt: s.string("The ISO 8601 timestamp when the diagram was last updated."),
});
const generatedDiagramSchema = s.looseRequiredObject("A diagram generated by Eraser AI.", {
  diagramType: diagramTypeSchema,
  code: s.string("The generated Eraser DSL source."),
});
const fileSchema = s.looseRequiredObject("An Eraser file and its current metadata.", {
  id: s.string("The unique file identifier."),
  fileUrl: s.string("The URL for viewing the file in Eraser.", { format: "uri" }),
  title: s.string("The file title."),
  author: s.string("The identifier of the file author."),
  folderId: s.nullableString("The containing folder identifier, or null for the root."),
  createdAt: s.string("The ISO 8601 timestamp when the file was created."),
  updatedAt: s.string("The ISO 8601 timestamp when the file was last updated."),
  linkAccess: linkAccessSchema,
});
const generationOutputSchema = s.object(
  "The generated Eraser diagram and links for using it.",
  {
    requestId: s.string("The identifier of the AI generation request."),
    imageUrl: s.string("The URL of the generated PNG image.", { format: "uri" }),
    createEraserFileUrl: s.string("The URL for creating an editable Eraser file.", {
      format: "uri",
    }),
    fileUrl: s.string("The URL of the Eraser file created by the request.", { format: "uri" }),
    diagrams: s.array("The diagrams generated by Eraser.", generatedDiagramSchema),
    relevantFilePaths: s.array(
      "Git repository file paths used as generation context.",
      s.string("A repository-qualified file path used as context."),
    ),
  },
  {
    optional: ["requestId", "imageUrl", "createEraserFileUrl", "fileUrl", "diagrams", "relevantFilePaths"],
  },
);
const fileIdInputSchema = s.object("Input identifying an Eraser file.", {
  fileId: s.nonEmptyString("The unique Eraser file identifier."),
});
const diagramIdInputSchema = s.object("Input identifying a diagram in an Eraser file.", {
  fileId: s.nonEmptyString("The unique Eraser file identifier."),
  diagramId: s.nonEmptyString("The unique diagram identifier."),
});

export const eraserActions: readonly ActionDefinition[] = [
  defineProviderAction(service, {
    name: "generate_diagram_from_prompt",
    description: "Generate or revise an Eraser diagram from a natural-language prompt.",
    requiredScopes: [],
    inputSchema: s.object(
      "Input for generating an Eraser diagram with AI.",
      {
        text: s.nonEmptyString("The natural-language prompt or source text for the diagram."),
        diagramType: diagramTypeSchema,
        mode: s.stringEnum("The Eraser AI model tier.", ["standard", "premium"]),
        priorRequestId: s.nonEmptyString("A previous request identifier to revise."),
        contextId: s.nonEmptyString("The AI preset identifier to use as context."),
        fileOptions: fileOptionsSchema,
      },
      { optional: ["diagramType", "mode", "priorRequestId", "contextId", "fileOptions"] },
    ),
    outputSchema: generationOutputSchema,
  }),
  defineProviderAction(service, {
    name: "generate_diagram_from_dsl",
    description: "Render Eraser DSL into a diagram image and optional editable Eraser file.",
    requiredScopes: [],
    inputSchema: s.object(
      "Input for rendering an Eraser DSL diagram.",
      {
        code: s.nonEmptyString("The Eraser DSL source to render."),
        diagramType: diagramTypeSchema,
        theme: s.stringEnum("The rendering theme.", ["light", "dark"]),
        background: s.boolean("Whether the rendered image should use a solid background."),
        imageQuality: s.integer("The image quality multiplier.", { minimum: 1, maximum: 3 }),
        fileOptions: fileOptionsSchema,
        title: s.nonEmptyString("The title for a file created from the diagram."),
      },
      { optional: ["theme", "background", "imageQuality", "fileOptions", "title"] },
    ),
    outputSchema: generationOutputSchema,
  }),
  defineProviderAction(service, {
    name: "list_files",
    description: "List files available to the authenticated Eraser team.",
    requiredScopes: [],
    inputSchema: s.object(
      "Filters and pagination for listing Eraser files.",
      {
        limit: s.integer("The maximum number of files to return, from 1 to 500.", {
          minimum: 1,
          maximum: 500,
        }),
        cursor: s.nonEmptyString("The cursor returned by a previous page."),
        folderId: s.nonEmptyString("The folder identifier used to filter files."),
        sort: s.stringEnum("The field and direction used to sort files.", [
          "createdAt",
          "-createdAt",
          "updatedAt",
          "-updatedAt",
        ]),
        author: s.nonEmptyString("The user identifier or email address used to filter files."),
      },
      { optional: ["limit", "cursor", "folderId", "sort", "author"] },
    ),
    outputSchema: s.object("A page of Eraser files.", {
      files: s.array("The files in the current page.", fileSchema),
      nextCursor: s.nullableString("The next-page cursor, or null when no next page exists."),
    }),
  }),
  defineProviderAction(service, {
    name: "create_file",
    description: "Create an Eraser file with optional Markdown content.",
    requiredScopes: [],
    inputSchema: s.object(
      "Input for creating an Eraser file.",
      {
        title: s.nonEmptyString("The file title; Eraser uses Untitled when omitted."),
        folderId: s.nonEmptyString("The folder in which to create the file."),
        document: s.string("The Markdown document content, including optional diagram code blocks."),
        linkAccess: linkAccessSchema,
      },
      { optional: ["title", "folderId", "document", "linkAccess"] },
    ),
    outputSchema: fileSchema,
  }),
  defineProviderAction(service, {
    name: "get_file",
    description: "Get an Eraser file and its current content.",
    requiredScopes: [],
    inputSchema: fileIdInputSchema,
    outputSchema: fileSchema,
  }),
  defineProviderAction(service, {
    name: "update_file",
    description: "Replace selected metadata or Markdown content of an Eraser file.",
    requiredScopes: [],
    inputSchema: s.object(
      "Input for updating an Eraser file.",
      {
        fileId: s.nonEmptyString("The unique Eraser file identifier."),
        title: s.nonEmptyString("The replacement file title."),
        folderId: s.nonEmptyString("The folder to which the file should be moved."),
        document: s.string("The replacement Markdown document content."),
      },
      { optional: ["title", "folderId", "document"] },
    ),
    outputSchema: fileSchema,
  }),
  defineProviderAction(service, {
    name: "archive_file",
    description: "Archive an Eraser file.",
    requiredScopes: [],
    inputSchema: fileIdInputSchema,
    outputSchema: s.object("The result of archiving an Eraser file.", {
      archived: s.boolean("Whether the file was archived."),
      fileUrl: s.string("The URL of the archived file.", { format: "uri" }),
    }),
  }),
  defineProviderAction(service, {
    name: "list_diagrams",
    description: "List diagrams contained in an Eraser file.",
    requiredScopes: [],
    inputSchema: fileIdInputSchema,
    outputSchema: s.array("The diagrams contained in the file.", diagramSchema),
  }),
  defineProviderAction(service, {
    name: "create_diagram",
    description: "Create a diagram from Eraser DSL inside an existing file.",
    requiredScopes: [],
    inputSchema: s.object(
      "Input for creating a diagram in an Eraser file.",
      {
        fileId: s.nonEmptyString("The unique Eraser file identifier."),
        diagramType: diagramTypeSchema,
        code: s.nonEmptyString("The Eraser DSL source for the new diagram."),
      },
      { optional: ["code"] },
    ),
    outputSchema: diagramSchema,
  }),
  defineProviderAction(service, {
    name: "get_diagram",
    description: "Get one diagram from an Eraser file.",
    requiredScopes: [],
    inputSchema: diagramIdInputSchema,
    outputSchema: diagramSchema,
  }),
  defineProviderAction(service, {
    name: "update_diagram",
    description: "Replace the Eraser DSL source of a diagram in a file.",
    requiredScopes: [],
    inputSchema: s.object("Input for updating a diagram in an Eraser file.", {
      fileId: s.nonEmptyString("The unique Eraser file identifier."),
      diagramId: s.nonEmptyString("The unique diagram identifier."),
      code: s.nonEmptyString("The replacement Eraser DSL source."),
    }),
    outputSchema: diagramSchema,
  }),
  defineProviderAction(service, {
    name: "delete_diagram",
    description: "Delete a diagram from an Eraser file.",
    requiredScopes: [],
    inputSchema: diagramIdInputSchema,
    outputSchema: s.object("The result of deleting an Eraser diagram.", {
      deleted: s.boolean("Whether the diagram was deleted."),
      fileUrl: s.string("The URL of the file that contained the diagram.", { format: "uri" }),
    }),
  }),
];
