import type { ActionDefinition } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";
import { defineProviderAction } from "../../core/provider-definition.ts";

const service = "zenventory";

const itemShape = {
  id: s.integer("The Zenventory item identifier."),
  sku: s.string("The item's SKU."),
  upc: s.string("The item's UPC."),
  description: s.string("The item's description."),
  category: s.string("The category used to group the item."),
  client: s.nullable(
    s.looseObject("The client that owns the item.", {
      id: s.integer("The client identifier."),
      name: s.string("The client name."),
    }),
  ),
  baseUom: s.string("The item's base unit of measurement."),
  unitCost: s.number("The cost to stock the item."),
  leadTime: s.integer("The item's lead time."),
  defaultEconOrder: s.integer("The default purchase-order quantity."),
  rrp: s.number("The item's recommended retail price."),
  price: s.number("The item's selling price."),
  active: s.boolean("Whether the item is active."),
  kit: s.boolean("Whether the item is a kit."),
  assembly: s.boolean("Whether the item is an assembly."),
  perishable: s.boolean("Whether the item has an expiration date."),
  trackLot: s.boolean("Whether the item is tracked by lot number."),
  serialized: s.boolean("Whether the item is tracked by serial number."),
  nonInventory: s.boolean("Whether the item does not have inventory."),
  weight: s.number("The item's weight."),
  storageLength: s.number("The item's storage length."),
  storageWidth: s.number("The item's storage width."),
  storageHeight: s.number("The item's storage height."),
  storageVolume: s.number("The item's calculated storage volume."),
  safetyStock: s.integer("The stock withheld from marketplace stock levels."),
  userField1: s.string("The first user-defined item field."),
  userField2: s.string("The second user-defined item field."),
  userField3: s.string("The third user-defined item field."),
  userField4: s.string("The fourth user-defined item field."),
  userField5: s.string("The fifth user-defined item field."),
  userField6: s.string("The sixth user-defined item field."),
  createdDate: s.string("The item creation timestamp."),
  modifiedDate: s.string("The item modification timestamp."),
  notes: s.string("Notes attached to the item."),
  additionalFields: s.looseObject("Optional units and bill-of-materials details requested for the item."),
};

const itemOutputSchema = s.looseObject("One Zenventory item.", itemShape);

const itemWriteShape = {
  sku: s.nonEmptyString("The item's SKU."),
  upc: s.string("The item's UPC."),
  description: s.string("The item's description."),
  category: s.string("The item's category."),
  baseUom: s.string("The item's base unit of measurement."),
  unitCost: s.number("How much the item costs to stock."),
  leadTime: s.integer("The item's lead time."),
  defaultEconOrder: s.integer("The default purchase-order quantity."),
  orderLimit: s.integer("The item's order limit."),
  rrp: s.number("The item's recommended retail price."),
  price: s.number("The item's selling price."),
  active: s.boolean("Whether the item is active."),
  kit: s.boolean("Whether the item is a kit made from other items."),
  assembly: s.boolean("Whether the item is stocked by combining other items."),
  perishable: s.boolean("Whether the item has an expiration date."),
  trackLot: s.boolean("Whether the item is tracked by lot number."),
  serialized: s.boolean("Whether the item is tracked by serial number."),
  nonInventory: s.boolean("Whether the item does not have inventory."),
  weight: s.number("The item's weight."),
  storageLength: s.number("The item's storage length."),
  storageWidth: s.number("The item's storage width."),
  storageHeight: s.number("The item's storage height."),
  safetyStock: s.integer("The stock withheld from marketplace stock levels."),
  userField1: s.string("The first user-defined item field."),
  userField2: s.string("The second user-defined item field."),
  userField3: s.string("The third user-defined item field."),
  userField4: s.string("The fourth user-defined item field."),
  userField5: s.string("The fifth user-defined item field."),
  userField6: s.string("The sixth user-defined item field, formatted as a date-time upstream."),
  notes: s.string("Notes for the item."),
};

const itemWriteOptionalFields: readonly (keyof typeof itemWriteShape)[] = [
  "upc",
  "description",
  "category",
  "baseUom",
  "unitCost",
  "leadTime",
  "defaultEconOrder",
  "orderLimit",
  "rrp",
  "price",
  "active",
  "kit",
  "assembly",
  "perishable",
  "trackLot",
  "serialized",
  "nonInventory",
  "weight",
  "storageLength",
  "storageWidth",
  "storageHeight",
  "safetyStock",
  "userField1",
  "userField2",
  "userField3",
  "userField4",
  "userField5",
  "userField6",
  "notes",
];

export const zenventoryActions: ActionDefinition[] = [
  defineProviderAction(service, {
    name: "list_items",
    description: "Search and page through items in Zenventory.",
    requiredScopes: [],
    inputSchema: s.object(
      "Filters and pagination for listing Zenventory items.",
      {
        searchFor: s.string("Text matched against item SKU, UPC, and description."),
        clientId: s.integer("The client identifier to filter by."),
        clientName: s.string("The client name to filter by when clientId is not provided."),
        category: s.string("The item category to filter by."),
        active: s.boolean("Whether to return active or inactive items."),
        nonInventory: s.boolean("Whether to include non-inventory items."),
        includeUnits: s.boolean("Whether to include item units of measurement."),
        includeBom: s.boolean("Whether to include item bill-of-materials details."),
        orderBy: s.stringEnum("The field used to order results.", [
          "id",
          "sku",
          "upc",
          "category",
          "unitCost",
          "price",
          "userField1",
          "userField2",
          "userField3",
          "userField4",
          "userField5",
          "userField6",
        ]),
        orderDir: s.stringEnum("The result ordering direction.", ["asc", "desc"]),
        page: s.integer("The result page number.", { minimum: 1 }),
        perPage: s.integer("The number of items per page.", { minimum: 20, maximum: 100 }),
      },
      {
        optional: [
          "searchFor",
          "clientId",
          "clientName",
          "category",
          "active",
          "nonInventory",
          "includeUnits",
          "includeBom",
          "orderBy",
          "orderDir",
          "page",
          "perPage",
        ],
      },
    ),
    outputSchema: s.object("A page of Zenventory items.", {
      items: s.array("The items in this result page.", itemOutputSchema),
      meta: s.looseObject("Pagination metadata for the result page.", {
        count: s.integer("The total number of matching items."),
        page: s.integer("The current result page."),
        perPage: s.integer("The number of items requested per page."),
        totalPages: s.integer("The total number of result pages."),
      }),
    }),
  }),
  defineProviderAction(service, {
    name: "get_item",
    description: "Get one Zenventory item by its identifier.",
    requiredScopes: [],
    inputSchema: s.object(
      "The item identifier and optional additional details to include.",
      {
        id: s.integer("The Zenventory item identifier.", { minimum: 1 }),
        includeUnits: s.boolean("Whether to include item units of measurement."),
        includeBom: s.boolean("Whether to include item bill-of-materials details."),
      },
      { optional: ["includeUnits", "includeBom"] },
    ),
    outputSchema: itemOutputSchema,
  }),
  defineProviderAction(service, {
    name: "create_item",
    description: "Create an item in Zenventory.",
    requiredScopes: [],
    inputSchema: s.object(
      "The fields used to create a Zenventory item.",
      {
        ...itemWriteShape,
        clientId: s.integer("The client identifier that owns the item."),
        clientName: s.string("The client name used when clientId is not provided."),
        assignToAllWarehouses: s.boolean("Whether to assign the item to all warehouses."),
        assignToWarehouse: s.boolean("Whether to assign the item to one warehouse."),
        warehouseId: s.integer("The warehouse identifier used for assignment."),
        warehouseName: s.string("The warehouse name used when warehouseId is not provided."),
        reorderLevel: s.integer("The reorder level for the warehouse assignment."),
      },
      {
        optional: [
          ...itemWriteOptionalFields,
          "clientId",
          "clientName",
          "assignToAllWarehouses",
          "assignToWarehouse",
          "warehouseId",
          "warehouseName",
          "reorderLevel",
        ],
      },
    ),
    outputSchema: itemOutputSchema,
  }),
  defineProviderAction(service, {
    name: "update_item",
    description: "Replace the editable fields of an existing Zenventory item.",
    requiredScopes: [],
    inputSchema: s.object(
      "The item identifier and replacement item fields.",
      {
        id: s.integer("The Zenventory item identifier.", { minimum: 1 }),
        ...itemWriteShape,
      },
      { optional: itemWriteOptionalFields },
    ),
    outputSchema: itemOutputSchema,
  }),
];
