import type { ActionDefinition } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";
import { defineProviderAction } from "../../core/provider-definition.ts";

const service = "screenshotbase";

const supportedCountryCodes = [
  "ae",
  "al",
  "am",
  "ar",
  "at",
  "au",
  "az",
  "ba",
  "bd",
  "be",
  "bg",
  "bh",
  "bn",
  "bo",
  "br",
  "bw",
  "by",
  "ca",
  "cg",
  "ch",
  "cl",
  "cm",
  "cn",
  "co",
  "cr",
  "cy",
  "cz",
  "de",
  "dk",
  "do",
  "dz",
  "ec",
  "ee",
  "eg",
  "es",
  "fi",
  "fr",
  "gb",
  "ge",
  "gh",
  "gr",
  "gt",
  "hk",
  "hr",
  "hu",
  "id",
  "ie",
  "il",
  "im",
  "in",
  "iq",
  "is",
  "it",
  "jm",
  "jo",
  "jp",
  "ke",
  "kg",
  "kh",
  "kr",
  "kw",
  "kz",
  "la",
  "li",
  "lk",
  "lt",
  "lu",
  "lv",
  "ma",
  "md",
  "mk",
  "mm",
  "mo",
  "mw",
  "mx",
  "my",
  "mz",
  "ng",
  "nl",
  "no",
  "nz",
  "om",
  "pa",
  "pe",
  "ph",
  "pk",
  "pl",
  "pr",
  "pt",
  "py",
  "qa",
  "ro",
  "rs",
  "ru",
  "sa",
  "sc",
  "se",
  "sg",
  "si",
  "sk",
  "sl",
  "th",
  "tj",
  "tm",
  "tn",
  "tr",
  "tw",
  "tz",
  "ua",
  "us",
  "uy",
  "uz",
  "ve",
  "vn",
  "za",
  "zm",
  "zw",
];

const quotaBucketSchema = s.object("One screenshotbase quota bucket.", {
  total: s.integer("The total requests available in this quota bucket."),
  used: s.integer("The requests already used in this quota bucket."),
  remaining: s.integer("The requests remaining in this quota bucket."),
});

const getQuotaStatusInputSchema = s.object("The input payload for retrieving screenshotbase quota status.", {});

const getQuotaStatusOutputSchema = s.object("The screenshotbase account quota status.", {
  accountId: s.nullable(s.integer("The screenshotbase account identifier when returned.")),
  month: quotaBucketSchema,
  grace: s.nullable(s.describe(quotaBucketSchema, "The grace quota bucket when available for the account.")),
});

const takeScreenshotInputSchema = s.object(
  "The input payload for capturing a webpage with screenshotbase.",
  {
    url: s.string("The complete HTTP or HTTPS webpage URL to capture.", { format: "uri" }),
    format: s.stringEnum("The image format for the hosted screenshot.", ["jpg", "jpeg", "png", "gif", "webp"]),
    quality: s.integer("The image quality to use when the format is jpg."),
    fullPage: s.boolean("Whether to capture the full scrollable page."),
    viewportWidth: s.integer("The browser viewport width in pixels."),
    viewportHeight: s.integer("The browser viewport height in pixels."),
    deviceScaleFactor: s.number("The browser device pixel ratio.", {
      minimum: 0.5,
      maximum: 3,
    }),
    ipCountryCode: s.stringEnum(
      "The lowercase ISO 3166-1 alpha-2 country code for the capture exit IP.",
      supportedCountryCodes,
    ),
    delay: s.integer("The seconds to wait after page load before capture.", {
      minimum: 0,
      maximum: 30,
    }),
    timeout: s.integer("The navigation timeout in seconds.", {
      minimum: 5,
      maximum: 60,
    }),
    waitUntil: s.stringEnum("The browser lifecycle event to wait for before capture.", [
      "load",
      "domcontentloaded",
      "networkidle0",
      "networkidle2",
    ]),
    blockCookieBanners: s.boolean("Whether to attempt to hide cookie-consent banners."),
    blockAds: s.boolean("Whether to attempt to block advertisements."),
    blockChats: s.boolean("Whether to attempt to hide chat widgets."),
    hideSelectors: s.array(
      "The CSS selectors of elements to hide before capture.",
      s.string("A CSS selector to hide.", { maxLength: 255 }),
    ),
    styles: s.string("The custom CSS to inject before capture.", { maxLength: 10_000 }),
    attachmentName: s.string("The output filename without an extension.", { maxLength: 255 }),
  },
  {
    optional: [
      "format",
      "quality",
      "fullPage",
      "viewportWidth",
      "viewportHeight",
      "deviceScaleFactor",
      "ipCountryCode",
      "delay",
      "timeout",
      "waitUntil",
      "blockCookieBanners",
      "blockAds",
      "blockChats",
      "hideSelectors",
      "styles",
      "attachmentName",
    ],
  },
);

const takeScreenshotOutputSchema = s.object("The hosted screenshot response.", {
  url: s.string("The public URL of the generated screenshot.", { format: "uri" }),
});

export const screenshotbaseActions: ActionDefinition[] = [
  defineProviderAction(service, {
    name: "get_quota_status",
    description: "Retrieve the current monthly and grace quota usage for screenshotbase.",
    requiredScopes: [],
    inputSchema: getQuotaStatusInputSchema,
    outputSchema: getQuotaStatusOutputSchema,
  }),
  defineProviderAction(service, {
    name: "take_screenshot",
    description: "Capture a webpage with screenshotbase and return a hosted screenshot URL.",
    requiredScopes: [],
    inputSchema: takeScreenshotInputSchema,
    outputSchema: takeScreenshotOutputSchema,
  }),
];
