import type { ActionDefinition } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";
import { defineProviderAction } from "../../core/provider-definition.ts";

const service = "altoviz";

const customerSchema = s.looseObject("An Altoviz customer record.", {
  id: s.optional(s.integer("The Altoviz customer ID.")),
  active: s.optional(s.boolean("Whether the customer is active.")),
  type: s.optional(s.stringEnum("The customer type.", ["Business", "Consumer", "Government"])),
  name: s.optional(s.nullableString("The display name generated by Altoviz.")),
  companyName: s.optional(s.nullableString("The customer's company name.")),
  firstName: s.optional(s.nullableString("The customer's first name.")),
  lastName: s.optional(s.nullableString("The customer's last name.")),
  email: s.optional(s.nullableString("The customer's email address.")),
  internalId: s.optional(s.nullableString("The customer ID from an external system.")),
  number: s.optional(s.nullableString("The customer number.")),
});

const paginationSchema = s.object(
  "Pagination metadata returned in Altoviz response headers.",
  {
    pageIndex: s.integer("The current one-based page index."),
    pageSize: s.integer("The requested page size."),
    pageCount: s.integer("The total number of pages when supplied by Altoviz."),
    recordCount: s.integer("The total number of matching records when supplied by Altoviz."),
    next: s.string("The relative URL of the next page."),
    previous: s.string("The relative URL of the previous page."),
  },
  { optional: ["pageCount", "recordCount", "next", "previous"] },
);

const listCustomersInputSchema = s.object(
  "Parameters for listing Altoviz customers.",
  {
    pageIndex: s.integer("The one-based page index.", { minimum: 1, default: 1 }),
    pageSize: s.integer("The number of customers per page.", { minimum: 1, maximum: 100, default: 10 }),
    orderBy: s.nonEmptyString("The Altoviz customer field ordering expression."),
    query: s.nonEmptyString("A full-text customer search query."),
  },
  { optional: ["pageIndex", "pageSize", "orderBy", "query"] },
);

const customerListOutputSchema = s.object("A page of Altoviz customers.", {
  customers: s.array("The customers on the current page.", customerSchema),
  pagination: paginationSchema,
});

const findCustomersInputSchema = s.object(
  "Criteria for finding Altoviz customers. At least one criterion is required.",
  {
    email: s.nonEmptyString("The exact customer email to find."),
    internalId: s.nonEmptyString("The customer identifier from an external system."),
    number: s.nonEmptyString("The Altoviz customer number to find."),
  },
  { optional: ["email", "internalId", "number"] },
);

const createCustomerInputSchema = s.object(
  "Fields for creating an Altoviz customer.",
  {
    active: s.boolean("Whether the customer is active."),
    type: s.stringEnum("The customer type.", ["Business", "Consumer", "Government"]),
    companyName: s.nullableString("The customer's company name."),
    firstName: s.nullableString("The customer's first name."),
    lastName: s.nullableString("The customer's last name."),
    email: s.nullable(s.email("The customer's email address.")),
    internalId: s.nullableString("The customer ID from an external system."),
    internalNotes: s.nullableString("Internal notes about the customer."),
    number: s.nullableString("The customer number."),
    phone: s.nullableString("The customer's phone number."),
    cellPhone: s.nullableString("The customer's mobile phone number."),
    title: s.nullableString("The customer's title."),
  },
  {
    optional: [
      "active",
      "type",
      "companyName",
      "firstName",
      "lastName",
      "email",
      "internalId",
      "internalNotes",
      "number",
      "phone",
      "cellPhone",
      "title",
    ],
  },
);

export const altovizActions: ActionDefinition[] = [
  defineProviderAction(service, {
    name: "list_customers",
    description: "List Altoviz customers with full-text search, ordering, and stable pagination metadata.",
    inputSchema: listCustomersInputSchema,
    outputSchema: customerListOutputSchema,
  }),
  defineProviderAction(service, {
    name: "get_customer",
    description: "Retrieve one Altoviz customer by its numeric customer ID.",
    inputSchema: s.object("The Altoviz customer to retrieve.", {
      customerId: s.positiveInteger("The numeric Altoviz customer ID."),
    }),
    outputSchema: s.object("The requested Altoviz customer.", { customer: customerSchema }),
  }),
  defineProviderAction(service, {
    name: "find_customers",
    description: "Find Altoviz customers by email, external-system ID, or customer number.",
    inputSchema: findCustomersInputSchema,
    outputSchema: s.object("Customers matching the supplied criteria.", {
      customers: s.array("The matching Altoviz customers.", customerSchema),
    }),
  }),
  defineProviderAction(service, {
    name: "create_customer",
    description: "Create a business, consumer, or government customer in Altoviz.",
    inputSchema: createCustomerInputSchema,
    outputSchema: s.object("The customer created by Altoviz.", { customer: customerSchema }),
  }),
];
