import type { ActionDefinition } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";
import { defineProviderAction } from "../../core/provider-definition.ts";

const service = "gptzero";

const probabilitySchema = s.nullable(
  s.number("A probability score between 0 and 1 when GPTZero returns the value.", {
    minimum: 0,
    maximum: 1,
  }),
);

const rawObjectSchema = s.looseObject("The raw GPTZero object for forward-compatible fields.");

const sentenceSchema = s.requiredObject("A normalized GPTZero sentence-level detection result.", {
  sentence: s.nullable(s.string("The sentence text returned by GPTZero.")),
  generatedProbability: probabilitySchema,
  perplexity: s.nullable(s.number("The perplexity score returned by GPTZero.")),
  highlightedForAi: s.nullable(s.boolean("Whether GPTZero highlighted this sentence as likely AI-generated.")),
  raw: rawObjectSchema,
});

const paragraphSchema = s.requiredObject("A normalized GPTZero paragraph-level detection result.", {
  completelyGeneratedProbability: probabilitySchema,
  sentenceCount: s.nullable(s.integer("The number of sentences GPTZero grouped into this paragraph.")),
  startSentenceIndex: s.nullable(s.integer("The index of the first sentence in this paragraph group.")),
  raw: rawObjectSchema,
});

const documentSchema = s.requiredObject("A normalized GPTZero document detection result.", {
  documentId: s.nullable(s.string("The GPTZero document ID when returned by the API.")),
  version: s.nullable(s.string("The GPTZero model or API version used for this document.")),
  classification: s.nullable(s.string("GPTZero's document classification, such as HUMAN_ONLY, MIXED, or AI_ONLY.")),
  resultMessage: s.nullable(s.string("GPTZero's human-readable result message.")),
  averageGeneratedProbability: probabilitySchema,
  completelyGeneratedProbability: probabilitySchema,
  overallBurstiness: s.nullable(s.number("The document burstiness score returned by GPTZero.")),
  classProbabilities: s.nullable(s.looseObject("GPTZero class probability fields such as ai, human, and mixed.")),
  confidenceCategory: s.nullable(s.string("GPTZero's confidence category when returned.")),
  confidenceScore: probabilitySchema,
  confidenceScoresRaw: s.nullable(s.looseObject("GPTZero confidence score details when returned by the API.")),
  writingStats: s.nullable(s.looseObject("GPTZero writing statistics when returned.")),
  paragraphs: s.array("Paragraph-level GPTZero results.", paragraphSchema),
  sentences: s.array("Sentence-level GPTZero results.", sentenceSchema),
  raw: rawObjectSchema,
});

export const gptzeroActions: ActionDefinition[] = [
  defineProviderAction(service, {
    name: "detect_text",
    description:
      "Detect whether a plain text document was generated by AI with GPTZero and return document, paragraph, and sentence-level scores.",
    inputSchema: s.object(
      "The input payload for detecting whether text was generated by AI with GPTZero.",
      {
        document: s.nonEmptyString("The plain text document to analyze."),
        version: s.nonEmptyString("Optional GPTZero API/model version to request."),
      },
      { required: ["document"] },
    ),
    outputSchema: s.requiredObject("The normalized GPTZero text detection response.", {
      version: s.nullable(s.string("The GPTZero API/model version returned for the response.")),
      scanId: s.nullable(s.string("The GPTZero scan ID when returned by the API.")),
      documents: s.array("Normalized GPTZero document results.", documentSchema),
      raw: rawObjectSchema,
    }),
  }),
];
